;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)

(ert-deftest eam-session-query-deadline-and-events ()
  "Slow Git jobs must allow timers, obey concurrency, and leave no jobs alive."
  (let ((original (symbol-function 'make-process))
        (eam-session-query-timeout 0.35)
        (ticks 0) jobs timer result)
    (unwind-protect
        (progn
          (setq timer (run-at-time 0.01 0.01 (lambda () (cl-incf ticks))))
          (cl-letf (((symbol-function 'make-process)
                     (lambda (&rest args)
                       (let* ((default-directory "/tmp/")
                              (process
                              (apply original
                                     (plist-put args :command
                                                (list "/bin/sleep" "10")))))
                         (push process jobs)
                         process))))
            (setq result (eam-app--branches
                          (cl-loop for n below 20 collect (format "/tmp/../tmp/%s/.." n)))))
          (should (> ticks 0))
          (should (= (length jobs) 8))
          (maphash (lambda (_ value) (should (equal value "unverified"))) result)
          (should (= (hash-table-count result) 20))
          (should-not (cl-some #'process-live-p jobs)))
      (when timer (cancel-timer timer))
      (dolist (process jobs) (when (process-live-p process) (delete-process process))))))

(ert-deftest eam-session-query-quit-cleanup ()
  (let ((original (symbol-function 'make-process)) jobs)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (let ((process (apply original
                                       (plist-put args :command '("/bin/sleep" "10")))))
                   (push process jobs) process)))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _) (signal 'quit nil))))
      (should (eq 'cancelled
                  (condition-case nil (eam-app--branches '("/tmp/"))
                    (quit 'cancelled)))))
    (should (= (length jobs) 1))
    (should-not (cl-some #'process-live-p jobs))))

(ert-deftest eam-session-query-output-bound ()
  (let ((original (symbol-function 'make-process)) jobs)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (let ((process
                        (apply original
                               (plist-put args :command
                                          (list (or (getenv "EAM_NATIVE_FIXTURE")
                                                          (error "Run scripts/test-native.sh")) "flood")))))
                   (push process jobs) process))))
      (should (equal (eam-app--branch "/tmp/") "—")))
    (should (process-get (car jobs) 'overflow))
    (should (<= (length (process-get (car jobs) 'branch-output)) 4096))
    (should-not (cl-some #'process-live-p jobs))))

(ert-deftest eam-session-query-concurrent-output ()
  "Every completed pipe must be drained before reading its branch output."
  (let ((original (symbol-function 'make-process))
        (eam-session-query-timeout 5.0)
        (directories (cl-loop for n below 24 collect (format "/fixture/%d" n))))
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (let ((default-directory "/tmp/"))
                   (apply original
                          (plist-put args :command '("/usr/bin/printf" "feature/한글\\n")))))))
      (let ((result (eam-app--branches directories)))
        (should (= (hash-table-count result) 24))
        (maphash (lambda (_ value) (should (equal value "feature/한글"))) result)))))

(ert-deftest eam-sessions-detached-selection-only-attaches ()
  (let ((eam-terminal--sessions nil) attached)
    (cl-letf (((symbol-function 'eam-app--live-inventory)
               (lambda (&optional _observe) '((sessions . (((session . "/tmp/persistent/session")
                                          (provider . "Codex") (directory . "/tmp/project")
                                          (attached_clients . 0)))))))
              ((symbol-function 'eam-attach) (lambda (directory) (setq attached directory)))
              ((symbol-function 'eam-new) (lambda (&rest _) (ert-fail "Restarted CLI"))))
      (save-window-excursion
        (eam-sessions)
        (should-not attached)
        (should (derived-mode-p 'eam-session-list-mode))
        (eam-session-list--open)
        (should (equal attached "/tmp/persistent/session"))))))

(ert-deftest eam-session-branch-local-and-unavailable ()
  (let ((directory (make-temp-file "eam-branch-" t)))
    (unwind-protect
        (let ((default-directory (file-name-as-directory directory)))
          (should (equal (eam-app--branch directory) "—"))
          (should (eq 0 (process-file "git" nil nil nil "init" "--quiet")))
          (should (eq 0 (process-file "git" nil nil nil "symbolic-ref" "HEAD"
                                     "refs/heads/feature/한글")))
          (should (equal (eam-app--branch directory) "feature/한글"))
          (should (equal (eam-app--branch (concat directory "/missing")) "—"))
          (cl-letf (((symbol-function 'process-file)
                     (lambda (&rest _) (ert-fail "Contacted remote host"))))
            (should (equal (eam-app--branch "/ssh:example:/project/") "—"))))
      (delete-directory directory t))))

(ert-deftest eam-session-switch-empty ()
  (let ((eam-terminal--sessions nil))
    (cl-letf (((symbol-function 'eam-app--live-inventory) (lambda (&optional _observe) nil)))
    (save-window-excursion
      (eam-sessions)
      (should (string-match-p "No sessions" (buffer-string)))))))

(ert-deftest eam-session-state-is-process-state ()
  (let* ((process (make-process :name "ai-state-test" :command '("/bin/sh" "-c" "exit 7")
                                :buffer nil :noquery t))
         (session (eam-terminal--session :process process)))
    (unwind-protect
        (progn
          (while (process-live-p process) (accept-process-output process 0.05))
          (should (equal (eam-app--process-state session) "exit(7)"))
          (setf (eam-terminal-error session) "disk error")
          (should (equal (eam-app--process-state session)
                         "exit(7); recording error")))
      (delete-process process))))

(ert-deftest eam-app-resources-independent-of-records ()
  "A relocated record directory must not redirect the manual or project root."
  (let ((eam-directory "/tmp/separate-ai-records/")
        (default-directory "/tmp/") opened)
    (unwind-protect
        (progn
          (eam-keys-mode 1)
          (should (equal default-directory "/tmp/"))
          (cl-letf (((symbol-function 'view-file) (lambda (path) (setq opened path))))
            (call-interactively (key-binding (kbd "C-c a ?"))))
          (should (file-exists-p opened))
          (should (equal opened (expand-file-name "docs/user-guide.md" eam--resource-directory))))
      (when (get-buffer "*EAM*") (kill-buffer "*EAM*")))))
(ert-deftest eam-help-read-only-and-keyboard-return ()
  (let* ((root (make-temp-file "eai-help-" t))
         (eam--resource-directory root)
         (configuration (current-window-configuration))
         buffer)
    (unwind-protect
        (progn
          (make-directory (expand-file-name "docs" root))
          (with-temp-file (expand-file-name "docs/user-guide.md" root)
            (insert "한글 사용 안내\n"))
          (eam-help)
          (setq buffer (current-buffer))
          (should buffer-read-only)
          (should view-mode)
          (should-error (insert "accidental edit") :type 'buffer-read-only)
          (call-interactively (key-binding (kbd "q")))
          (should-not (eq (window-buffer) buffer)))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (set-window-configuration configuration)
      (delete-directory root t))))
(ert-deftest eam-editor-invalid-override-does-not-start-server ()
  (let ((eam-emacsclient-executable "/missing/eam-client"))
    (cl-letf (((symbol-function 'server-start) (lambda () (ert-fail "Started before finding client"))))
      (should-error (eam-terminal--editor-command) :type 'user-error))))
(ert-deftest eam-resume-arguments-and-invalid-id ()
  (let ((eam-terminal--sessions nil) (eam-cli-notifications nil) calls)
    (cl-letf (((symbol-function 'eam--executable) #'identity)
              ((symbol-function 'eam-persistent--start)
               (lambda (name dir args)
                 (push (list name nil args dir) calls)
                 (eam-terminal--session))))
      (should-error (eam-resume "Codex" "/tmp" "--last") :type 'user-error)
      (should-not calls)
      (eam-resume "Claude" "/tmp" "")
      (should (equal (nth 2 (car calls)) '("--resume")))
      (eam-resume "Codex" "/tmp" "01a07f90-db19-7910-87cd-76a13e97d3f4")
      (should (equal (nth 2 (car calls)) '("resume" "01a07f90-db19-7910-87cd-76a13e97d3f4"))))))
(ert-deftest eam-draft-keeps-parent-suffix ()
  "Opening same-project drafts in reverse order preserves terminal identity."
  (let* ((name "*Codex terminal: /tmp/project*")
         (first (eam-terminal--session :name "Codex" :directory "/tmp/project/"
                                           :output (generate-new-buffer name)))
         (second (eam-terminal--session :name "Codex" :directory "/tmp/project/"
                                            :output (generate-new-buffer name))))
    (unwind-protect
        (progn
          (should (equal (buffer-name (eam-terminal--ensure-draft second))
                         "*Codex draft: /tmp/project*<2>"))
          (should (equal (buffer-name (eam-terminal--ensure-draft first))
                         "*Codex draft: /tmp/project*"))
          (with-current-buffer (eam-terminal-input second)
            (should (eq eam-terminal--current second))))
      (dolist (s (list first second))
        (dolist (b (list (eam-terminal-input s) (eam-terminal-output s)))
          (when (buffer-live-p b) (kill-buffer b)))))))
(ert-deftest eam-app-entry-and-keyboard-commands ()
  (let ((processes (process-list))
        (windows (length (window-list)))
        (sessions eam-terminal--sessions)
        (before eam-keys-mode) called)
    (unwind-protect
        (progn
          (eam-keys-mode 1)
          (should (equal processes (process-list)))
          (should (equal sessions eam-terminal--sessions))
          (should (= (length (window-list)) windows))
          (should (eq (key-binding (kbd "C-c a n")) #'eam-new))
          (should (eq (lookup-key eam-command-map (kbd "q")) 'eam-quit)))
      (eam-keys-mode (if before 1 -1))
      (when (get-buffer "*EAM*") (kill-buffer "*EAM*")))))
(ert-deftest eam-keys-disable-restores-bindings ()
  (let ((before eam-keys-mode)
        (global-map (copy-keymap global-map)))
    (unwind-protect
        (progn
          (eam-keys-mode -1)
          (define-key global-map (kbd "C-c a") #'ignore)
          (eam-keys-mode 1)
          (should (eq (key-binding (kbd "C-c a b")) #'eam-draft))
          (eam-keys-mode -1)
          (should (eq (key-binding (kbd "C-c a")) #'ignore)))
      (eam-keys-mode (if before 1 -1)))))
(ert-deftest eam-app-project-selection-and-cancel ()
  (let ((use-dialog-box t) (provider "Claude") calls)
    (cl-letf (((symbol-function 'read-string) (lambda (&rest _) ""))
              ((symbol-function 'completing-read)
               (lambda (_prompt collection _predicate require-match &rest _)
                 (should (equal collection '("Claude" "Codex")))
                 (should require-match)
                 provider))
              ((symbol-function 'read-directory-name)
               (lambda (&rest _) (should-not use-dialog-box) "/tmp/한글 프로젝트/"))
              ((symbol-function 'file-directory-p) (lambda (_path) t))
              ((symbol-function 'eam-terminal-start-provider)
               (lambda (p d &optional _name) (push (cons p d) calls))))
      (call-interactively #'eam-new)
      (setq provider "codex")
      (call-interactively #'eam-new)
      (should (equal calls '(("Codex" . "/tmp/한글 프로젝트/") ("Claude" . "/tmp/한글 프로젝트/")))))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil)))
              ((symbol-function 'read-directory-name) (lambda (&rest _) (ert-fail "Project after provider cancel")))
              ((symbol-function 'eam-terminal-start-provider) (lambda (&rest _) (ert-fail "Started after cancel"))))
      (should (eq (condition-case nil (call-interactively #'eam-new) (quit 'cancelled)) 'cancelled)))
    (should use-dialog-box)
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Claude"))
              ((symbol-function 'read-directory-name)
               (lambda (&rest _) (should-not use-dialog-box) "/tmp/"))
              ((symbol-function 'read-string) (lambda (prompt &rest _)
                                               (should (string-prefix-p "Session name" prompt)) ""))
              ((symbol-function 'eam-persistent--start)
               (lambda (&rest _) (push 'resumed calls) (eam-terminal--session))))
      (call-interactively #'eam-resume)
      (should (eq (car calls) 'resumed)))
    (should use-dialog-box)))

(ert-deftest eam-provider-validation-and-cancel ()
  (cl-letf (((symbol-function 'eam-terminal-start) (lambda (&rest _) (ert-fail "Unexpected CLI start"))))
    (should-error (eam-terminal-start-provider "Unknown" "/tmp/") :type 'user-error))
  (dolist (command '(eam-new eam-resume))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil)))
              ((symbol-function 'make-process) (lambda (&rest _) (ert-fail "Process after cancel")))
              ((symbol-function 'make-directory) (lambda (&rest _) (ert-fail "Directory after cancel"))))
      (should (eq (condition-case nil (call-interactively command) (quit 'cancelled)) 'cancelled)))))

(ert-deftest eam-all-provider-entry-points-use-persistence ()
  (let (calls)
    (cl-letf (((symbol-function 'eam-persistent--start)
               (lambda (p d args) (should-not args) (push (list p d) calls)))
              ((symbol-function 'eam-terminal-start)
               (lambda (&rest _) (ert-fail "Started an Emacs-owned provider")))
              ((symbol-function 'read-directory-name) (lambda (&rest _) "/tmp/")))
      (eam-new "Claude" "/tmp/")
      (eam-terminal-start-provider "Codex" "/tmp/")
      (eam-new "Claude" "/tmp/")
      (should (equal (reverse calls) '(("Claude" "/tmp/") ("Codex" "/tmp/") ("Claude" "/tmp/")))))))

(ert-deftest eam-public-command-names-and-existing-keys ()
  (dolist (command '(eam-new eam-detach eam-detach-all eam-attach eam-quit eam-sessions
                    eam-resume eam-status eam-focus eam-edit-input eam-draft
                    eam-draft-add-selection eam-paste
                       eam-history eam-history-open

                     eam-history-previous-page eam-history-next-page
                    eam-history-latest))
    (should (commandp command)))
  (dolist (command '(eam-switch eam-close eam-terminate eam-enter eam-escape eam-up eam-down eam-interrupt eam-demo-new eam-demo-send eam-demo-stop eam-demo-input eam-demo-stress eam eam-app eam-app-switch eam-app-resume eam-terminal-resume
                    eam-persistent-start eam-persistent-detach eam-persistent-status
                    eam-new-connected-session eam-new-session eam-send eam-stop
                    eam-input eam-stress eam-terminal--close eam--close-buffer-session))
    (should-not (commandp command)))
  (dolist (binding '(("l" . eam-sessions) ("r" . eam-resume)
                     ("e" . eam-edit-input) ("p" . eam-paste)
                     ("a" . eam-attach) ("q" . eam-quit)
                     ("i" . eam-status)))
    (should (eq (lookup-key eam-command-map (kbd (car binding))) (cdr binding)))))

(ert-deftest eam-minimal-command-completion-and-no-start-screen ()
  (should-not (fboundp 'eam))
  (should (eq (lookup-key eam-command-map (kbd "a")) 'eam-attach))
  (let (visible)
    (mapatoms (lambda (symbol)
                (when (and (string-prefix-p "eam-" (symbol-name symbol))
                           (commandp symbol)
                           (command-completion-default-include-p symbol (current-buffer)))
                  (push (symbol-name symbol) visible))))
    (should (equal (sort visible #'string<)
                   '("eam-attach" "eam-caffeine-mode" "eam-detach" "eam-detach-all" "eam-draft" "eam-edit-input" "eam-help" "eam-history" "eam-history-open" "eam-keys-mode" "eam-native-build" "eam-new" "eam-next-session" "eam-note" "eam-notifications" "eam-paste" "eam-persist" "eam-previous-session" "eam-prompt" "eam-quick" "eam-quit" "eam-rename" "eam-resume" "eam-review-selection" "eam-sessions" "eam-status" "eam-usage"))))
  (eam-keys-mode 1)
  (should-not (get-buffer "*EAM*"))
  (should-not (key-binding (kbd "C-c a RET")))
  (should-not (fboundp 'eam-enter)))

(ert-deftest eam-project-task-feature-removed ()
  (should-not (lookup-key eam-command-map (kbd "T")))
  (dolist (command '(eam-task-register eam-task-run eam-task-rerun eam-task-output))
    (should-not (fboundp command))))

(ert-deftest eam-common-prefix-has-no-duplicate-commands ()
  (should-not (lookup-key eam-command-map (kbd "P")))
  (mapatoms (lambda (command)
              (when (and (commandp command) (string-prefix-p "eam-" (symbol-name command)))
                (should (<= (length (where-is-internal command eam-command-map)) 1))))))

(ert-deftest eam-sessions-prefix-shows-only-detached ()
  (let ((eam-terminal--sessions nil) attached)
    (cl-letf (((symbol-function 'eam-app--live-inventory)
               (lambda (&optional _observe) '((sessions . (((session . "/tmp/attached") (provider . "Claude")
                                          (directory . "/tmp/project") (attached_clients . 1))
                                         ((session . "/tmp/detached") (provider . "Codex")
                                          (directory . "/tmp/project") (attached_clients . 0)))))))
              ((symbol-function 'eam-attach) (lambda (directory) (setq attached directory))))
      (save-window-excursion
        (let ((current-prefix-arg '(4))) (call-interactively #'eam-sessions))
        (should-not attached)
        (should-not (string-match-p "Claude" (buffer-string)))
        (eam-session-list--open)
        (should (equal attached "/tmp/detached"))))))

(ert-deftest eam-attach-interactive-selects-detached-without-directory-prompt ()
  (let (filter)
    (cl-letf (((symbol-function 'eam-sessions) (lambda (only) (setq filter only)))
              ((symbol-function 'read-directory-name) (lambda (&rest _) (ert-fail "Directory prompt"))))
      (call-interactively #'eam-attach)
      (should filter))))
(ert-deftest eam-requested-session-bindings ()
  (dolist (binding '(("n" . eam-new) ("l" . eam-sessions) ("d" . eam-detach) ("q" . eam-quit)
                     ("b" . eam-draft) ("m" . eam-notifications)
                     ("y" . eam-draft-add-selection)
                     ("w c" . eam-worktree-create) ("w o" . eam-worktree-open)
                     ("w s" . eam-worktree-start) ("w d" . eam-worktree-remove)
                     ))
    (should (eq (lookup-key eam-command-map (kbd (car binding))) (cdr binding)))))

(ert-deftest eam-resume-default-opens-native-picker ()
  (let ((eam-terminal--sessions nil) calls)
    (dolist (provider '("Claude" "Codex"))
      (cl-letf (((symbol-function 'eam--read-provider) (lambda () provider))
                ((symbol-function 'read-directory-name) (lambda (&rest _) "/tmp/"))
                ((symbol-function 'read-string)
                 (lambda (prompt &rest _) (should (string-prefix-p "Session name" prompt)) ""))
                ((symbol-function 'eam-persistent--start)
                 (lambda (name directory args &optional _label)
                   (push (list name directory args) calls)
                   (eam-terminal--session))))
        (call-interactively #'eam-resume)))
    (should (equal (reverse calls)
                   '(("Claude" "/tmp/" ("--resume"))
                     ("Codex" "/tmp/" ("resume")))))))

(ert-deftest eam-workspace-feature-is-removed ()
  (should-not (locate-library "eam-workspace"))
  (should-not (fboundp 'eam-workspace-save))
  (should (eq (lookup-key eam-command-map (kbd "s")) #'eam-quick)))

(ert-deftest eam-detach-all-snapshots-registry-and-continues-after-errors ()
  (let* ((a (generate-new-buffer " *eam-detach-all-a*"))
         (b (generate-new-buffer " *eam-detach-all-b*"))
         (other (generate-new-buffer " *eam-unrelated*"))
         (first (eam-terminal--session :output a))
         (second (eam-terminal--session :output b))
         (eam-terminal--sessions (list first second))
         calls)
    (unwind-protect
        (cl-letf (((symbol-function 'eam-detach)
                   (lambda ()
                     (push (current-buffer) calls)
                     (if (eq (current-buffer) a)
                         (progn (setq eam-terminal--sessions nil) (error "Fixture failure"))
                       (kill-buffer (current-buffer))))))
          (with-current-buffer other (should-error (eam-detach-all) :type 'user-error))
          (should (equal (nreverse calls) (list a b)))
          (should (buffer-live-p other))
          (should-not (buffer-live-p b))
          (should (= 0 (eam-detach-all))))
      (mapc (lambda (buffer) (when (buffer-live-p buffer) (kill-buffer buffer)))
            (list a b other)))))
