;;; caffeine-test.el --- Actual macOS sleep assertions -*- lexical-binding: t; -*-
(require 'ert)
(require 'seq)
(require 'eam-caffeine)

(defun eam-caffeine-test--assertions (pid)
  (with-temp-buffer
    (unless (zerop (call-process "/usr/bin/pmset" nil t nil "-g" "assertions"))
      (error "pmset failed"))
    (let ((pattern (format "pid %d(caffeinate)" pid)))
      (seq-filter (lambda (line) (string-match-p (regexp-quote pattern) line))
                  (split-string (buffer-string) "\n")))))

(ert-deftest eam-caffeine-prevents-display-and-system-idle-sleep ()
  (skip-unless (eq system-type 'darwin))
  (let ((eam-caffeine--process nil) (eam-caffeine-mode nil)
        (kill-emacs-hook nil) pid assertions)
    (unwind-protect
        (progn
          (eam-caffeine-mode 1)
          (setq pid (process-id eam-caffeine--process))
          (let ((first eam-caffeine--process))
            (eam-caffeine-mode 1)
            (should (eq first eam-caffeine--process)))
          (let ((deadline (+ (float-time) 3)))
            (while (and (< (length assertions) 2) (< (float-time) deadline))
              (accept-process-output nil .05)
              (setq assertions (eam-caffeine-test--assertions pid))))
          (should (seq-some (lambda (line) (string-match-p "PreventUserIdleDisplaySleep" line)) assertions))
          (should (seq-some (lambda (line) (string-match-p "PreventUserIdleSystemSleep" line)) assertions))
          (eam-caffeine-mode -1)
          (should-not eam-caffeine--process)
          (let ((deadline (+ (float-time) 3)))
            (while (and (eam-caffeine-test--assertions pid) (< (float-time) deadline))
              (accept-process-output nil .05)))
          (should-not (eam-caffeine-test--assertions pid)))
      (eam-caffeine--stop))))

(ert-deftest eam-caffeine-auto-tracks-all-attachments-and-preserves-manual ()
  (let ((eam-caffeine-mode nil) (eam-caffeine--auto-owned nil)
        (eam-caffeine--automatic-change nil))
    (cl-letf (((symbol-function 'eam-caffeine-mode)
               (lambda (arg) (setq eam-caffeine-mode (> arg 0)))))
      (eam-caffeine--sync '((sessions . (((attached_clients . 1) (remote . t))))))
      (should eam-caffeine-mode)
      (should eam-caffeine--auto-owned)
      (eam-caffeine--sync '((sessions . (((attached_clients . 1) (remote . nil))))))
      (should eam-caffeine-mode)
      (eam-caffeine--sync '((unverified . ("unknown"))))
      (should eam-caffeine-mode)
      (eam-caffeine--sync '((sessions . (((attached_clients . 0))))))
      (should-not eam-caffeine-mode)
      (setq eam-caffeine-mode t eam-caffeine--auto-owned nil)
      (eam-caffeine--sync '((sessions . nil)))
      (should eam-caffeine-mode))))
