;;; cli-soak.el --- Explicit real-CLI idle/menu soak, never in test.sh -*- lexical-binding: t; -*-
(require 'eam-terminal)
(defvar ai-soak-sessions nil)
(defvar ai-soak-results nil)
(defvar ai-soak-directory (getenv "EMACS_AI_SOAK_DIR"))
(defvar ai-soak-start (float-time))
(defun ai-soak-wait (seconds)
  (let ((end (+ (float-time) seconds)))
    (while (< (float-time) end) (accept-process-output nil .05))))
(defun ai-soak-screen (s)
  (set-window-buffer (selected-window) (eam-terminal-output s))
  (ghostel--redraw-now (eam-terminal-output s) t)
  (with-current-buffer (eam-terminal-output s) (buffer-string)))
(defun ai-soak-key (s key)
  (with-current-buffer (eam-terminal-output s) (eam-terminal-key key)))
(defun ai-soak-menu (s provider)
  "Measure paste/Enter to parsed menu, including forced batch redraw."
  (let ((start (float-time)) found
        (pattern (if (equal provider "codex") "Select Model and Effort" "Select model")))
    (ai-soak-screen s)
    (with-current-buffer (eam-terminal-output s) (ghostel-paste-string "/model"))
    ;; Wait for paste before Enter; never send a second Enter into a menu.
    (ai-soak-wait .2)
    (ai-soak-key s "return")
    (while (and (not (setq found (string-match-p pattern (ai-soak-screen s))))
                (< (- (float-time) start) 8))
      (accept-process-output nil .05))
    (let ((ms (* 1000 (- (float-time) start))))
      (when found (ai-soak-key s "escape") (ai-soak-wait .2))
      `((provider . ,provider) (menu_seen . ,(if found t :json-false))
        (paste_to_menu_ms . ,ms)))))
(defun ai-soak-rss (pid)
  (with-temp-buffer
    (if (zerop (call-process "ps" nil t nil "-o" "rss=" "-p" (number-to-string pid)))
        (string-to-number (buffer-string)) 0)))
(defun ai-soak-save ()
  (with-temp-file (expand-file-name "samples.json" ai-soak-directory)
    (insert (json-encode (vconcat (reverse ai-soak-results))))))
(make-directory ai-soak-directory t)
(set-frame-size (selected-frame) 120 50)
(delete-other-windows)
(unwind-protect
    (progn
      (dotimes (i 4)
        (let* ((provider (if (< i 2) "claude" "codex"))
               (workspace (expand-file-name (concat "../20260908/" provider "/workspace") ai-soak-directory))
               (args (if (equal provider "claude") '("--permission-mode" "manual")
                       (list "-c" (concat "projects={" (json-encode-string workspace) "={trust_level=\"trusted\"}}")
                             "--sandbox" "read-only" "--ask-for-approval" "on-request"
                             "-c" "approvals_reviewer=\"user\"")))
               (s (eam-terminal-start (format "soak-%s-%d" provider i)
                                          (eam--executable provider) args workspace)))
          (push (cons provider s) ai-soak-sessions)))
      (setq ai-soak-sessions (nreverse ai-soak-sessions))
      (ai-soak-wait 15)
      (dotimes (round 11)
        (let (rows)
          (dolist (entry ai-soak-sessions)
            (let* ((s (cdr entry)) (screen (ai-soak-screen s))
                   (menu (ai-soak-menu s (car entry))))
              (unless (eq (alist-get 'menu_seen menu) t)
                (with-temp-file (expand-file-name "failed-menu.txt" ai-soak-directory)
                  (insert (ai-soak-screen s)))
                (error "Menu failed; stop without sending further input"))
              (push (append menu
                            `((cli_pid . ,(process-id (eam-terminal-process s)))
                              (cli_rss_kib . ,(ai-soak-rss (process-id (eam-terminal-process s))))
                              (output_chars . ,(length screen))
                              (raw_bytes . ,(file-attribute-size (file-attributes (eam-terminal-file s))))
                              (output_undo_disabled . ,(with-current-buffer (eam-terminal-output s)
                                                         (eq buffer-undo-list t))))) rows)))
          (push `((elapsed_s . ,(- (float-time) ai-soak-start))
                  (emacs_rss_kib . ,(ai-soak-rss (emacs-pid)))
                  (sessions . ,(vconcat (nreverse rows)))) ai-soak-results)
          (ai-soak-save)
          (princ (format "Round %d complete\n" round)))
        (unless (= round 10) (ai-soak-wait 30)))
      ;; Kill one idle CLI abruptly; survivors must still answer native menus.
      (let* ((victim (cdar ai-soak-sessions))
             (proc (eam-terminal-process victim)))
        (signal-process (process-id proc) 9)
        (ai-soak-wait 1)
        (let ((survivors (mapcar (lambda (entry) (ai-soak-menu (cdr entry) (car entry)))
                                (cdr ai-soak-sessions))))
          (with-temp-file (expand-file-name "abrupt-exit.json" ai-soak-directory)
            (insert (json-encode
                     `((victim_status . ,(symbol-name (process-status proc)))
                       (output_retained . ,(buffer-live-p (eam-terminal-output victim)))
                       (archive_bytes . ,(file-attribute-size (file-attributes (eam-terminal-file victim))))
                       (survivors . ,(vconcat survivors)))))))))
  (dolist (entry ai-soak-sessions)
    (let ((s (cdr entry)))
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach)))))
  (server-force-delete))
