;;; cli-startup-errors.el --- Installed CLI error probes -*- lexical-binding: t; -*-
;; Explicit local integration test, excluded from test.sh. No model prompts.
(load (expand-file-name "tests/terminal-test.el"))
(ert-deftest eam-installed-cli-startup-errors ()
  (let* ((eam-directory (make-temp-file "ai-cli-errors-" t))
         (healthy (eam-terminal-start
                   "healthy" (eam--executable "python3")
                   (list (expand-file-name "tests/terminal-fixture.py")
                         (expand-file-name "received.jsonl" eam-directory))
                   eam-directory))
         sessions)
    (unwind-protect
        (dolist (provider '("claude" "codex"))
          (dolist (args '(("--eam-intentionally-invalid-option") ("--version")))
            (let* ((s (eam-terminal-start provider (eam--executable provider)
                                               args eam-directory))
                   (p (eam-terminal-process s)))
              (push s sessions)
              (eam-terminal-test-wait (lambda () (not (process-live-p p))))
              (should (eq (process-status p) 'exit))
              (should (eq (= (process-exit-status p) 0) (equal args '("--version"))))
              (should (process-live-p (eam-terminal-process healthy)))
              (should (buffer-live-p (eam-terminal-output s)))
              (with-current-buffer (eam-terminal-output s)
                (should (string-match-p "exited (" (eam-terminal--header)))
                (should (eq buffer-undo-list t))
                (should-error (eam-terminal-key "return") :type 'user-error))
              (let ((raw (with-temp-buffer
                           (insert-file-contents (eam-terminal-file s))
                           (buffer-string))))
                (should (> (length raw) 0))
                (when (equal args '("--eam-intentionally-invalid-option"))
                  (should (string-match-p "eam-intentionally-invalid-option" raw)))
                (message "%s %s: exit=%d archive-bytes=%d"
                         provider (car args) (process-exit-status p) (string-bytes raw))))))
      (dolist (s (cons healthy sessions))
        (when (buffer-live-p (eam-terminal-output s))
          (with-current-buffer (eam-terminal-output s) (eam-detach))))
      (server-force-delete)
      (delete-directory eam-directory t))))
