;;; cli-exit.el --- Native exit updates lifecycle -*- lexical-binding: t; -*-
(require 'eam-app)
(let* ((root (make-temp-file "eam-cli-exit-" t))
       (eam-directory (expand-file-name "records/" root))
       (eam-cli-notifications nil)
       (eam-record-terminal t)
       (gate (expand-file-name "exit" root))
       (script (format "import os,time; print('종료 전 기록',flush=True)\nwhile not os.path.exists(%S): time.sleep(.02)\nraise SystemExit(7)" gate))
       sessions directories retained-draft)
  (unwind-protect
      (progn
        (dolist (provider '("Claude" "Codex"))
          (cl-letf (((symbol-function 'eam--executable) (lambda (_) (executable-find "python3"))))
            (let ((s (eam-persistent--start provider root (list "-c" script))))
              (push s sessions)
              (push (buffer-local-value 'eam-terminal-persistent-directory (eam-terminal-output s)) directories))))
        (unless (= 2 (length (alist-get 'sessions (eam-app--live-inventory))))
          (error "Running sessions missing"))
        (with-current-buffer (eam-terminal-output (car sessions))
          (eam-draft)
          (setq retained-draft (current-buffer))
          (insert "보존할 미저장 초안"))
        (write-region "exit" nil gate nil 'silent)
        (let ((deadline (+ (float-time) 10)))
          (while (and (< (float-time) deadline)
                      (cl-some (lambda (s) (buffer-live-p (eam-terminal-output s))) sessions))
            (accept-process-output nil .05)))
        (dolist (s sessions)
          (when (buffer-live-p (eam-terminal-output s)) (error "Exited display remains"))
          (when (memq s eam-terminal--sessions) (error "Exited session remains"))
          (unless (with-temp-buffer (insert-file-contents (eam-terminal-file s))
                                    (search-forward "종료 전 기록" nil t))
            (error "Archive lost")))
        (dolist (directory directories)
          (let ((state (alist-get 'status (eam-persistent--call "inspect" `((session . ,directory))))))
            (unless (and (equal (alist-get 'state state) "stopped")
                         (equal (alist-get 'exit_code state) "7"))
              (error "Wrong exit state: %S" state))))
        (unless (and (buffer-live-p retained-draft)
                     (with-current-buffer retained-draft
                       (equal (buffer-string) "보존할 미저장 초안")))
          (error "Unsaved draft lost"))
        (when (alist-get 'sessions (eam-app--live-inventory))
          (error "Terminated sessions remain in live inventory"))
        (message "PASS: both native CLI exits -> terminated(7), server stopped, archives retained"))
    (dolist (directory directories)
      (ignore-errors (eam-persistent--call "stop" `((session . ,directory)))))
    (dolist (s sessions)
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach))))
    (when (buffer-live-p retained-draft)
      (with-current-buffer retained-draft (set-buffer-modified-p nil) (kill-buffer)))
    (delete-directory root t)))
