;;; connect-test.el -*- lexical-binding: t; -*-
(load (expand-file-name "support/eam-demo.el" (file-name-directory (or load-file-name buffer-file-name))) nil t)
(require 'eam-connect)
(require 'ert)
(defconst eam-test--fixture
  (expand-file-name "fake-provider.py" (file-name-directory (or load-file-name buffer-file-name))))
(ert-deftest eam-connect-bounded-disk-projection ()
  (let* ((eam-directory (make-temp-file "ai-connect-test-" t))
         (eam-buffer-limit 128)
         (s (eam--create)))
    (unwind-protect
        (progn
          (setf (eam-session-display-offset s) 0)
          (eam-connect--filter s (make-string 100000 ?한))
          (with-current-buffer (eam-session-output s)
            (should (= 0 (buffer-size)))
            (eam-connect--flush s)
            (should (<= (buffer-size) 128))
            (should (= (eam--size s) 300000))
            (should (eq buffer-undo-list t))
            (eam-history-previous-page)
            (let ((frozen (buffer-string)))
              (eam-connect--filter s "추가🙂")
              (eam-connect--flush s)
              (should (equal frozen (buffer-string))))
            (eam-history-latest)
            (let ((latest (buffer-string)))
              (eam-connect--flush s)
              (should (equal latest (buffer-string)))
              (should (string-suffix-p "추가🙂" latest)))))
      (with-current-buffer (eam-session-output s) (eam-detach))
      (delete-directory eam-directory t))))
(ert-deftest eam-connect-real-pipe-fixtures ()
  (dolist (provider '(claude codex))
    (let* ((eam-directory (make-temp-file "ai-connect-process-" t))
           (process-environment (copy-sequence process-environment))
           (eam-python-executable (eam--executable "python3"))
           (s nil))
      (setenv "EMACS_AI_FIXTURE_REQUESTS" (expand-file-name "requests" eam-directory))
      (setenv "CODEX_HOME" eam-directory)
      (unwind-protect
          (cl-letf (((symbol-function 'eam--executable) (lambda (_) eam-test--fixture)))
            (setq s (eam-connect-new provider eam-directory))
            (should-not (eam-session-process s))
            (dotimes (_ 2)
              (with-current-buffer (eam-session-input s)
                (erase-buffer) (insert "한글 그대로")
                (eam-demo-send)
                (should-error (eam-demo-send) :type 'user-error)
                (should-not (eq buffer-undo-list t)))
              (let ((deadline (+ (float-time) 10)))
                (while (and (process-live-p (eam-session-process s)) (< (float-time) deadline))
                  (accept-process-output nil .02)))
              (accept-process-output nil .05)
              (should (eq (eam-session-status s) 'completed))
              (should-not (eam-session-timer s))
              (should-not (process-live-p (eam-session-stderr-process s)))
              (with-current-buffer (eam-session-output s)
                (should (string-suffix-p "한글🙂\n" (buffer-string)))
                (should (eq buffer-undo-list t)))))
        (when s (with-current-buffer (eam-session-output s) (eam-detach)))
        (delete-directory eam-directory t)))))
