;;; eam-test.el -*- lexical-binding: t; -*-
(load (expand-file-name "support/eam-demo.el" (file-name-directory (or load-file-name buffer-file-name))) nil t)
(require 'ert)
(require 'eam)
(ert-deftest eam-live-header-tracks-persisted-bytes ()
  (let* ((eam-directory (make-temp-file "eam-header-" t))
         (eam-buffer-limit 128)
         (s (eam--create)))
    (unwind-protect
        (with-current-buffer (eam-session-output s)
          (eam--append s "한🙂")
          (should (string-match-p "saved 7 B | shown 2 chars" header-line-format))
          (eam--append s (make-string 200 ?가))
          (should (string-match-p "saved 607 B | shown 128 chars" header-line-format))
          (eam-history-previous-page)
          (let ((header header-line-format))
            (eam--append s "끝")
            (should (equal header header-line-format)))
          (eam-history-latest)
          (should (string-match-p "saved 610 B" header-line-format)))
      (with-current-buffer (eam-session-output s) (eam-detach))
      (delete-directory eam-directory t))))
(defmacro eam-test--with (&rest body)
  `(let* ((eam-directory (make-temp-file "eam-test-" t))
          (eam-buffer-limit 128)
          (s (eam--create)))
     (unwind-protect (progn ,@body)
       (with-current-buffer (eam-session-output s) (eam-detach))
       (delete-directory eam-directory t))))
(ert-deftest eam-missing-archive-does-not-leak-buffers ()
  (eam-test--with
   (let ((before (buffer-list))
         (registered (copy-sequence eam--sessions)))
     (unwind-protect
         (progn
           (should-error (eam-history-open
                          (expand-file-name "missing.txt" eam-directory)))
           (should-not (cl-set-difference (buffer-list) before))
           (should (equal registered eam--sessions))
           (eam--append s "정상 세션 유지")
           (with-current-buffer (eam-session-output s)
             (should (string-match-p "정상 세션 유지" (buffer-string)))))
       (dolist (buffer (cl-set-difference (buffer-list) before)) (kill-buffer buffer))))))
(ert-deftest eam-bounded-roundtrip ()
  (eam-test--with
   (let ((original (apply #'concat (make-list 100 "한글🙂abc\n코드\n"))) pages)
     (eam--append s original)
     (with-current-buffer (eam-session-output s)
       (should (<= (buffer-size) 128))
       (should (eq buffer-undo-list t))
       (eam-history-previous-page)
       (push (buffer-string) pages)
       (while (> (car (eam-session-cursor s)) 0)
         (eam-history-previous-page)
         (should (<= (buffer-size) 128))
         (push (buffer-string) pages))
       (should (equal (apply #'concat pages) original))
       (let ((forward (list (buffer-string))))
         (while (< (cdr (eam-session-cursor s)) (eam--size s))
           (eam-history-next-page)
           (push (buffer-string) forward))
         (should (equal (apply #'concat (nreverse forward)) original)))
       (let ((frozen (buffer-string)))
         (eam--append s "추가 응답")
         (should (equal frozen (buffer-string))))
       (eam-history-latest)
       (should (string-suffix-p "추가 응답" (buffer-string)))
       (should (<= (buffer-size) 128)))
     (should (equal (with-temp-buffer
                      (insert-file-contents (eam-session-file s)) (buffer-string))
                    (concat original "추가 응답"))))))
(ert-deftest eam-input-undo-and-lifecycle ()
  (eam-test--with
   (with-current-buffer (eam-session-input s)
     (insert "한글 입력") (undo-boundary)
     (insert " 수정") (undo-boundary)
     (undo 1)
     (should (equal (buffer-string) "한글 입력"))
     (eam-demo-send)
     (should (timerp (eam-session-timer s)))
     (should-error (eam-demo-send) :type 'user-error)
     (should-not (eq buffer-undo-list t))
     (kill-buffer (current-buffer))
     (should-not (eam-session-timer s))
     (should-not (memq s eam--sessions)))))
(ert-deftest eam-write-failure-stops ()
  (eam-test--with
   (setf (eam-session-file s) (expand-file-name "missing/file" eam-directory)
         (eam-session-remaining s) 10)
   (eam--tick s)
   (should (eam-session-error s))
   (should (= 0 (eam-session-remaining s)))))
(ert-deftest eam-session-isolation-and-completion ()
  (eam-test--with
   (let ((other (eam--create)))
     (unwind-protect
         (progn
           (eam--append s "첫 번째 세션")
           (setf (eam-session-remaining other) 2)
           (eam--tick other) (eam--tick other)
           (should (= 0 (eam-session-remaining other)))
           (should-not (eam-session-timer other))
           (with-current-buffer (eam-session-output s)
             (should (equal (buffer-string) "첫 번째 세션")))
           (with-current-buffer (eam-session-output other)
             (should (<= (buffer-size) 128)))
           (should-not (equal (eam-session-file s) (eam-session-file other))))
       (with-current-buffer (eam-session-output other) (eam-detach))))))
(ert-deftest eam-reopen-bounded ()
  (eam-test--with
   (eam--append s (make-string 100000 ?한))
   (let ((other (eam--create (eam-session-file s))))
     (unwind-protect
         (progn
           (with-current-buffer (eam-session-output other)
             (should (<= (buffer-size) 128))
             (should-not (eq (current-buffer) (eam-session-output s))))
           (with-current-buffer (eam-session-input other)
             (insert "보관 기록 수정 금지")
             (should-error (eam-demo-send) :type 'user-error)))
       (with-current-buffer (eam-session-output other) (eam-detach))))))
