;;; gui-review-fixture.el --- Review GUI fixture without AI -*- lexical-binding: t; -*-
(require 'eam-app)
(require 'eam-review)
(let* ((root (file-name-as-directory (getenv "EMACS_AI_REVIEW_ROOT")))
       (eam-directory (expand-file-name "records/" root)))
  (when (file-exists-p root) (error "Use a new fixture directory"))
  (make-directory root t)
  (eam-terminal-start "Review-test" (executable-find "python3")
                           '("-c" "print('Review fixture: no AI; draft inspection only')") root)
  (eam-keys-mode 1)
  (switch-to-buffer (get-buffer-create "*Review GUI diff*"))
  (setq default-directory root)
  (insert "diff --git a/example.py b/example.py\n--- a/example.py\n+++ b/example.py\n@@ -1 +1 @@\n-print('before')\n+print('after')\n")
  (diff-mode)
  (goto-char (point-min))
  (delete-other-windows))
