;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-history)
(ert-deftest eam-history-send-failure-stops-worker ()
  "A broken input pipe must not leave a search worker attached to the viewer."
  (let* ((eam-directory (make-temp-file "ai-history-send-" t))
         (file (expand-file-name "test.ansi" eam-directory)) s worker)
    (unwind-protect
        (progn
          (with-temp-file file (insert "unchanged archive"))
          (setq s (eam--create file))
          (with-current-buffer (eam-session-output s)
            (cl-letf (((symbol-function 'process-send-string)
                       (lambda (process _text)
                         (setq worker process)
                         (signal 'file-error '("Broken search pipe")))))
              (should-error (eam-history-search "archive") :type 'file-error))
            (should worker)
            (should-not (process-live-p worker))
            (should-not eam-history--process)
            (should (buffer-live-p (current-buffer))))
          (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string))
                         "unchanged archive")))
      (when (and s (buffer-live-p (eam-session-output s)))
        (with-current-buffer (eam-session-output s) (eam-detach)))
      (delete-directory eam-directory t))))
(ert-deftest eam-history-search-pages-and-cancel ()
  (let* ((eam-directory (make-temp-file "ai-history-" t))
         (eam-buffer-limit 128)
         (file (expand-file-name "test.ansi" eam-directory))
         (needle "한글🙂") s)
    (unwind-protect
        (progn
          (with-temp-file file
            (insert (make-string 65534 ?x) needle "\n\e[31m" needle "\e[0m\n"))
          (setq s (eam--create file))
          (with-current-buffer (eam-session-output s)
            (eam-history-search needle)
            (let ((end (+ (float-time) 8)))
              (while (and eam-history--process (< (float-time) end)) (accept-process-output nil .01)))
            (should-not eam-history--process)
            (should (= eam-history--offset 65534))
            (should (<= (buffer-size) 128))
            (should (search-backward needle nil t))
            (eam-history-next)
            (let ((end (+ (float-time) 8)))
              (while (and eam-history--process (< (float-time) end)) (accept-process-output nil .01)))
            (should (= eam-history--offset (+ 65534 (string-bytes needle) 6)))
            (should eam-history-hide-colors)
            (should-not (string-match-p "\e\\[31m" (buffer-string)))
            (should (eq buffer-undo-list t))
            (eam-history-search "absent")
            (should-not eam-history--offset)
            (let ((process eam-history--process))
              (eam-detach)
              (should-not (process-live-p process)))))
      (when (and s (buffer-live-p (eam-session-output s)))
        (with-current-buffer (eam-session-output s) (eam-detach)))
      (delete-directory eam-directory t))))

(ert-deftest eam-history-render-colors-across-page-boundaries ()
  (let* ((eam-directory (make-temp-file "eam-color-" t))
         (eam-buffer-limit 128)
         (file (expand-file-name "colors.ansi" eam-directory)) session)
    (unwind-protect
        (progn
          (with-temp-file file (insert "\e[31;44m한글 RED\e[0m plain"))
          (setq session (eam--create file))
          (with-current-buffer (eam-session-output session)
            ;; A page starting inside an escape sequence must not show fragments.
            (eam--page session 3 (eam--size session))
            (should (equal (buffer-string) "한글 RED plain"))
            (let ((face (get-text-property (point-min) 'face)))
              (should face)
              (should (cl-some (lambda (spec) (plist-get spec :foreground)) face))
              (should (cl-some (lambda (spec) (plist-get spec :background)) face)))
            (goto-char (point-min))
            (search-forward "plain")
            (should-not (get-text-property (1- (point)) 'face))
            ;; Starting after the color code also inherits the preceding state.
            (eam--page session 8 (eam--size session))
            (should (get-text-property (point-min) 'face))
            (should (<= (buffer-size) eam-buffer-limit))
            (should (eq buffer-undo-list t))
            (eam-history-toggle-colors)
            (should (string-match-p "\e\\[31;44m" (buffer-string))))
          (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string))
                         "\e[31;44m한글 RED\e[0m plain")))
      (when (and session (buffer-live-p (eam-session-output session)))
        (with-current-buffer (eam-session-output session) (eam-detach)))
      (delete-directory eam-directory t))))

(ert-deftest eam-history-terminal-rows-do-not-collapse ()
  (let* ((eam-directory (make-temp-file "eam-rows-" t))
         (eam-buffer-limit 128)
         (file (expand-file-name "rows.ansi" eam-directory)) session)
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "요청\e[1B\e[31m응답\e[0m\e[3;1H다음 행\r진행\r\n끝"))
          (setq session (eam--create file))
          (with-current-buffer (eam-session-output session)
            (should-not truncate-lines)
            (should word-wrap)
            (should (equal (buffer-string) "요청\n응답\n다음 행\n진행\n끝"))
            (goto-char (point-min))
            (search-forward "응답")
            (should (get-text-property (1- (point)) 'face))
            (should (eq buffer-undo-list t))
            ;; Splitting the row movement across the page keeps its boundary.
            (eam--page session (+ (string-bytes "요청") 2) (eam--size session))
            (should (string-prefix-p "\n응답" (buffer-string)))
            (should (<= (buffer-size) 128))))
      (when (and session (buffer-live-p (eam-session-output session)))
        (with-current-buffer (eam-session-output session) (eam-detach)))
      (delete-directory eam-directory t))))
