;;; memory-recovery.el --- PTY streaming followed by full session cleanup -*- lexical-binding: t; -*-
(require 'eam-terminal)
(defvar recovery-root default-directory)
(defvar recovery-dir (getenv "EMACS_AI_RECOVERY_DIR"))
(defvar recovery-start (float-time))
(defvar recovery-rounds (string-to-number (or (getenv "EMACS_AI_RECOVERY_ROUNDS") "4")))
(defvar recovery-seconds (or (getenv "EMACS_AI_RECOVERY_SECONDS") "8"))
(unless (and (<= 1 recovery-rounds 100) (<= 1 (string-to-number recovery-seconds) 10))
  (error "Use 1..100 rounds and 1..10 seconds"))
(defun recovery-sample (round phase)
  (let* ((file (expand-file-name (format "footprint-%d-%s.jsonl" round phase) recovery-dir))
         (status (call-process (eam--executable "python3") nil nil nil
                               (expand-file-name "tests/process-footprint.py" recovery-root)
                               (number-to-string (emacs-pid)) file "--duration" ".1" "--interval" ".1"))
         (usage (with-temp-buffer (insert-file-contents file)
                                 (json-parse-string (buffer-string) :object-type 'alist))))
    (unless (zerop status) (error "Footprint reader failed"))
    (with-temp-buffer
      (insert (json-encode
               `((round . ,round) (phase . ,phase) (elapsed . ,(- (float-time) recovery-start))
                 (rss . ,(alist-get 'resident_bytes usage))
                 (footprint . ,(alist-get 'physical_footprint_bytes usage))
                 (buffers . ,(length (buffer-list)))
                 (live_processes . ,(cl-count-if #'process-live-p (process-list)))
                 (process_objects . ,(length (process-list)))
                 (sessions . ,(length eam-terminal--sessions))
                 (timers . ,(length timer-list)))))
      (insert "\n")
      (write-region (point-min) (point-max) (expand-file-name "samples.jsonl" recovery-dir) t 'silent))))
(when (file-exists-p recovery-dir) (error "Use a fresh recovery directory"))
(make-directory recovery-dir t)
(let ((eam-directory recovery-dir) sessions)
  (unwind-protect
      (progn
        (garbage-collect)
        (recovery-sample 0 "baseline")
        (dotimes (round recovery-rounds)
          (dotimes (i 4)
            (let ((directory (expand-file-name (format "producer-%d-%d" round i) recovery-dir)))
              (make-directory directory)
              (push (eam-terminal-start
                     (format "memory-%d" i) (eam--executable "python3")
                     (list (expand-file-name "tests/stream-fixture.py" recovery-root) directory recovery-seconds)
                     recovery-root) sessions)))
          (let ((deadline (+ (float-time) 15)))
            (while (and (cl-some (lambda (s) (process-live-p (eam-terminal-process s))) sessions)
                        (< (float-time) deadline))
              (accept-process-output nil .02)))
          (dolist (s sessions)
            (when (or (process-live-p (eam-terminal-process s)) (eam-terminal-error s))
              (error "Fixture did not finish cleanly"))
            (switch-to-buffer (eam-terminal-output s))
            (ghostel--redraw-now (current-buffer) t))
          (recovery-sample (1+ round) "streamed")
          (garbage-collect)
          (recovery-sample (1+ round) "streamed-gc")
          (dolist (s sessions)
            (with-current-buffer (eam-terminal-output s) (eam-detach)))
          (setq sessions nil)
          (recovery-sample (1+ round) "closed")
          (garbage-collect)
          (accept-process-output nil .05)
          (recovery-sample (1+ round) "closed-gc")
          (garbage-collect)
          (recovery-sample (1+ round) "settled-gc")
          (when eam-terminal--sessions (error "Session registry not empty"))
          (message "Recovery round %d done" (1+ round))))
    (dolist (s sessions)
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach))))
    (server-force-delete)))
