;;; native-history-test.el --- Native viewer checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-native-history)
(require 'eam-terminal)
(ert-deftest eam-native-history-bounded-readonly-pages ()
  (let* ((root (make-temp-file "eam-native-" t))
         (file (expand-file-name "native.jsonl" root))
         (eam-buffer-limit 4096))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert (json-encode `((type . "user") (message . ((role . "user") (content . ,(make-string 200000 ?한)))))) "\n"))
          (with-temp-buffer
            (eam-native-history-mode)
            (setq eam-native-history--entry `((provider . "Claude") (id . "one") (path . ,file)))
            (eam-native-history-latest)
            (should buffer-read-only)
            (should (eq buffer-undo-list t))
            (should (<= (buffer-size) (eam--limit)))
            (should (> eam-native-history--start 0))
            (let ((last eam-native-history--start))
              (eam-native-history-previous)
              (should (< eam-native-history--start last)))
            (setq eam-native-history--prompt t)
            (eam-native-history-latest)
            (should (= eam-native-history--start 0))
            (eam-native-history-next)
            (should (> eam-native-history--start 0)))
          (should (equal (directory-files root nil "^[^.]") '("native.jsonl"))))
      (delete-directory root t))))
(ert-deftest eam-native-history-reader-error-cleans-worker ()
  (should-error (eam-native-history--query '((action . "list") (provider . "unknown") (root . "/tmp"))) :type 'user-error)
  (should-not (get-buffer " *eam-native-result*"))
  (should-not (cl-find-if (lambda (p) (and (process-live-p p) (string-prefix-p "eam-native-history" (process-name p)))) (process-list))))
(ert-deftest eam-native-history-default-recording-option ()
  (should-not (default-value 'eam-record-terminal)))

(ert-deftest eam-history-current-never-opens-conversation-picker ()
  (require 'eam-persistent)
  (with-temp-buffer
    (setq-local eam-terminal-persistent-directory "/tmp/current-session")
    (let (shown)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _) (ert-fail "Unexpected conversation picker")))
                ((symbol-function 'eam-native-history--query)
                 (lambda (q)
                   (should (equal (alist-get 'action q) "current"))
                   (should (equal (alist-get 'session q) "/tmp/current-session"))
                   '((entry . ((provider . "Claude") (id . "current"))))))
                ((symbol-function 'eam-native-history--show)
                 (lambda (entry &optional _) (setq shown entry))))
        (eam-history)
        (should (equal (alist-get 'id shown) "current")))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _) (ert-fail "Unexpected fallback picker")))
                ((symbol-function 'eam-native-history--query)
                 (lambda (_) (user-error "Current conversation not identified"))))
        (should-error (eam-history) :type 'user-error)))))
