;;; native-package-install.el --- Install and build with no Python -*- lexical-binding: t; -*-
(require 'package)
(require 'ert)
(defvar eam-directory)
(defvar eam-native-executable)
(defvar eam-native--build-process)
(let* ((root (getenv "EAM_TEST_ROOT"))
       (temp (make-temp-file "eam-native-install-" t))
       (user-emacs-directory (expand-file-name "profile/" temp))
       (package-user-dir (expand-file-name "packages/" temp))
       (package-archives nil)
       (package-check-signature nil)
       (eam-directory (expand-file-name "records/" temp))
       (default-directory temp)
       binary)
  (unwind-protect
      (progn
        (package-initialize)
        (let ((dependency (expand-file-name "var/deps/ghostel/lisp" root)))
          (push (cons 'ghostel (list (package-desc-create :name 'ghostel :version '(0 53 0)
                                                         :dir dependency :kind 'tar))) package-alist)
          (add-to-list 'load-path dependency)
          (require 'ghostel)
          (push 'ghostel package-activated-list))
        (package-install-file (getenv "EAM_PACKAGE_TAR"))
        (should (autoloadp (symbol-function 'eam-new)))
        (require 'eam-app)
        (should-not (file-exists-p eam-directory))
        (should-not (process-list))
        (should (file-in-directory-p eam--resource-directory package-user-dir))
        (should-not (directory-files-recursively eam--resource-directory "\\.py\\'"))
        (should-not (file-directory-p (expand-file-name "native/examples" eam--resource-directory)))
        ;; Exercise the real first-use builder in the relocated installed package.
        (should-error (eam-native--executable) :type 'user-error)
        (should (processp eam-native--build-process))
        (let ((deadline (+ (float-time) 900)))
          (while (and (process-live-p eam-native--build-process) (< (float-time) deadline))
            (accept-process-output nil .1))
          (should-not (process-live-p eam-native--build-process)))
        (let ((eam-native-auto-build nil))
          (setq binary (eam-native--executable)))
        (should (file-executable-p binary))
        (should (file-in-directory-p binary eam-directory))
        (let ((eam-native-cargo-executable "/missing/cargo"))
          (should (equal binary (eam-native--executable))))
        (dolist (file '("usage-test.el" "session-list-test.el" "native-history-test.el" "history-test.el" "notifications-test.el" "pty-backend-test.el"))
          (load (expand-file-name (concat "tests/" file) root) nil t))
        ;; A rebuild should not occur merely because tests override the records directory.
        (setq eam-native-executable binary)
        (let ((stats (ert-run-tests-batch "^eam-\\(account-\\|usage-\\|list-\\|native-history\\|history-\\|notifications-\\|pty-backend\\)")))
          (should (= 0 (ert-stats-completed-unexpected stats))))
        (let ((record (expand-file-name "keep.txt" eam-directory)))
          (with-temp-file record (insert "보존"))
          (package-delete (cadr (assq 'eam package-alist)) t)
          (should (file-exists-p record))
          (should (file-executable-p binary)))
        (princ "Installed native package: first build, cache without Cargo, no Python, PTY/history, deletion preservation passed\n"))
    (delete-directory temp t)))
