;;; native-build-test.el --- Async native build regression -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-native)
(defun eam-native-test-wait (predicate)
  (let ((end (+ (float-time) 6)))
    (while (and (not (funcall predicate)) (< (float-time) end))
      (accept-process-output nil .02))
    (should (funcall predicate))))
(ert-deftest eam-native-build-async-visible-deduplicated-and-cached ()
  (let* ((root (make-temp-file "eam-build-" t))
         (eam-native--build-process nil)
         (eam-native-executable nil)
         (eam-native-auto-build t)
         (eam-native-cargo-executable (expand-file-name "cargo" root))
         (target (expand-file-name "target" root))
         (runtime (getenv "EAM_NATIVE_BIN"))
         timer tick process)
    (unwind-protect
        (save-window-excursion
          (with-temp-file eam-native-cargo-executable
            (insert "#!/bin/sh\necho 'fixture: compiling'\nsleep 1\nmkdir -p "
                    (shell-quote-argument (expand-file-name "release" target))
                    "\ncp " (shell-quote-argument runtime) " "
                    (shell-quote-argument (expand-file-name "release/eam-runtime" target))
                    "\necho 'fixture: done'\n"))
          (set-file-modes eam-native-cargo-executable #o700)
          (cl-letf (((symbol-function 'eam-native--cache) (lambda () target)))
            (setq timer (run-at-time .1 nil (lambda () (setq tick t))))
            (let ((start (float-time)))
              (should-error (eam-native--executable) :type 'user-error)
              (should (< (- (float-time) start) .8)))
            (setq process eam-native--build-process)
            (should (process-live-p process))
            (should (get-buffer-window (process-buffer process)))
            (should (eq process (eam-native-build)))
            (eam-native-test-wait
             (lambda () (with-current-buffer (process-buffer process)
                          (string-match-p "fixture: compiling" (buffer-string)))))
            (should (process-live-p process))
            (eam-native-test-wait (lambda () (not (process-live-p process))))
            (should tick)
            (should (zerop (process-exit-status process)))
            ;; Process status can change before its queued sentinel runs.
            (eam-native-test-wait
             (lambda () (with-current-buffer (process-buffer process)
                          (string-match-p "Ready" header-line-format))))
            (delete-file eam-native-cargo-executable)
            (should (file-executable-p (eam-native--executable)))))
      (when timer (cancel-timer timer))
      (when (process-live-p process) (delete-process process))
      (delete-directory root t))))
(ert-deftest eam-native-build-failure-keeps-log-and-allows-retry ()
  (let* ((root (make-temp-file "eam-build-fail-" t))
         (eam-native--build-process nil)
         (eam-native-cargo-executable (expand-file-name "cargo" root))
         process)
    (unwind-protect
        (save-window-excursion
          (with-temp-file eam-native-cargo-executable
            (insert "#!/bin/sh\necho 'fixture compiler error'\nexit 7\n"))
          (set-file-modes eam-native-cargo-executable #o700)
          (cl-letf (((symbol-function 'eam-native--cache) (lambda () root)))
            (dotimes (_ 2)
              (setq process (eam-native-build))
              (eam-native-test-wait (lambda () (not (process-live-p process))))
              (should (= 7 (process-exit-status process)))
              (eam-native-test-wait
               (lambda () (with-current-buffer (process-buffer process)
                            (and (string-match-p "fixture compiler error" (buffer-string))
                                 (string-match-p "failed" header-line-format))))))))
      (when (process-live-p process) (delete-process process))
      (delete-directory root t))))

(ert-deftest eam-native-cache-changes-with-bundled-source ()
  (let* ((root (make-temp-file "eam-source-hash-" t))
         (eam-directory (expand-file-name "data" root))
         (src (expand-file-name "src" root)))
    (unwind-protect
        (progn
          (make-directory src)
          (make-directory (expand-file-name "web" root))
          (dolist (file '("Cargo.toml" "Cargo.lock" "src/main.rs" "web/app.js"))
            (with-temp-file (expand-file-name file root) (insert "original")))
          (cl-letf (((symbol-function 'eam-native--source) (lambda () root)))
            (let ((previous (eam-native--cache)))
              (should (equal previous (eam-native--cache)))
              (dolist (file '("Cargo.toml" "Cargo.lock" "src/main.rs" "web/app.js"))
                (with-temp-file (expand-file-name file root) (insert "modified"))
                (should-not (equal previous (eam-native--cache)))
                (setq previous (eam-native--cache)))
              (rename-file (expand-file-name "main.rs" src) (expand-file-name "other.rs" src))
              (should-not (equal previous (eam-native--cache))))))
      (delete-directory root t))))
