;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(ert-deftest eam-notifications-desktop-origin-and-opt-in ()
  "Desktop fallback titles use the originating session, even during polling."
  (let ((origin (generate-new-buffer "notice origin"))
        (eam-notifications--entries nil)
        (eam-notification-desktop nil)
        calls)
    (unwind-protect
        (with-temp-buffer
          (cl-letf (((symbol-function 'ghostel-default-notify)
                     (lambda (title body)
                       (push (list (current-buffer) title body) calls))))
            (eam-notifications--receive origin "" "default off")
            (should-not calls)
            (setq eam-notification-desktop t)
            (eam-notifications--receive origin "" "enabled")
            (should (equal calls (list (list origin "" "enabled"))))
            (eam-notifications--receive origin "" "enabled")
            (should (= (length calls) 1))
            (should-not (eq (current-buffer) origin)))
          (cl-letf (((symbol-function 'ghostel-default-notify)
                     (lambda (&rest _) (error "backend unavailable"))))
            (eam-notifications--receive origin "" "backend failure")
            (should (equal (eam-notice-body
                            (car eam-notifications--entries)) "backend failure"))))
      (kill-buffer origin))))
(ert-deftest eam-notifications-attribution-and-navigation ()
  (let ((a (generate-new-buffer "notice 한글")) (b (generate-new-buffer "notice other"))
        (eam-notifications--entries nil) selected)
    (unwind-protect
        (cl-letf (((symbol-function 'process-send-string) (lambda (&rest _) (ert-fail "Input sent")))
                  ((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (setq selected buffer))))
          (eam-notifications--receive a "Claude" "확인 요청")
          (eam-notifications--receive a "Claude" "확인 요청")
          (eam-notifications--receive b "Claude" "확인 요청")
          (should (= (length eam-notifications--entries) 2))
          (should (= (eam-notice-count (cadr eam-notifications--entries)) 2))
          (eam-notification-next)
          (should (eq selected a))
          (should (eam-notice-read (cadr eam-notifications--entries)))
          (eam-notification-next)
          (should (eq selected b))
          (should-error (eam-notification-next) :type 'user-error))
      (kill-buffer a) (kill-buffer b))))
(ert-deftest eam-notifications-bounds-and-closed ()
  (let ((buffer (generate-new-buffer "notice bounds"))
        (eam-notifications--entries nil)
        (eam-notification-limit 3)
        (eam-notification-text-limit 12))
    (unwind-protect
        (progn
          (dotimes (n 20)
            (eam-notifications--receive buffer (number-to-string n) (make-string 1000 ?가)))
          (should (= (length eam-notifications--entries) 3))
          (should (= (length (eam-notice-body (car eam-notifications--entries))) 12))
          (eam-notifications)
          (should (eq buffer-undo-list t))
          (should (= (length tabulated-list-entries) 3))
          (kill-buffer buffer)
          (should-error (eam-notification-next) :type 'user-error)
          (eam-notifications-refresh)
          (should (equal (aref (cadar tabulated-list-entries) 1) "closed")))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (when (get-buffer "*AI notifications*") (kill-buffer "*AI notifications*")))))

(ert-deftest eam-notifications-real-pty ()
  "Fragmented UTF-8 OSC 9 and 777 reach the correct sessions and disk archive."
  (let ((fixture (getenv "EAM_NATIVE_FIXTURE")))
    (let ((eam-record-terminal t)
          (eam-directory (make-temp-file "ai-notice-pty-" t))
          (eam-notifications--entries nil)
          (eam-notification-desktop nil)
          sessions)
      (unwind-protect
          (progn
            (dolist (label '("alpha" "beta"))
              (push (eam-terminal-start
                     label fixture
                     (list "notification" label)
                     eam-directory) sessions))
            (let ((deadline (+ (float-time) 8)))
              (while (and (< (length eam-notifications--entries) 4)
                          (< (float-time) deadline))
                (accept-process-output nil 0.02)))
            (should (= (length eam-notifications--entries) 4))
            (dolist (session sessions)
              (let ((entries (cl-remove-if-not
                              (lambda (entry) (eq (eam-notice-buffer entry)
                                                 (eam-terminal-output session)))
                              eam-notifications--entries)))
                (should (= (length entries) 2))
                (should (cl-find "확인 요청" entries :key #'eam-notice-body :test #'equal))
                (should (cl-find (concat (eam-terminal-name session) " 한글 완료")
                                 entries :key #'eam-notice-body :test #'equal)))
              (should (= 0 (file-attribute-size
                            (file-attributes (eam-terminal-input-file session)))))
              (with-temp-buffer
                (insert-file-contents (eam-terminal-file session))
                (should (search-forward (concat "\e]9;" (eam-terminal-name session)
                                                " 한글 완료\a") nil t))
                (should (search-forward (concat "\e]777;notify;" (eam-terminal-name session)
                                                ";확인 요청\e\\") nil t)))))
        (dolist (session sessions)
          (when (buffer-live-p (eam-terminal-output session))
            (with-current-buffer (eam-terminal-output session) (eam-detach))))
        (server-force-delete)
        (delete-directory eam-directory t)))))

(ert-deftest eam-notifications-cli-start-and-resume-options ()
  (let ((eam-cli-notifications t) (eam-terminal--sessions nil) calls)
    (cl-letf (((symbol-function 'eam--executable) #'identity)
              ((symbol-function 'eam-persistent--start)
               (lambda (name _dir extra-args)
                 (push (cons name (append (eam-notifications-cli-args name) extra-args)) calls)
                 (eam-terminal--session))))
      (dolist (provider '("Claude" "Codex"))
        (eam-terminal-start-provider provider "/tmp/")
        (let ((start-args (cdar calls)))
          (should start-args)
          (eam-resume provider "/tmp/" "")
          (should (equal (cdar calls)
                         (append start-args (if (equal provider "Claude") '("--resume") '("resume")))))))
    (let ((eam-cli-notifications nil))
      (should-not (eam-notifications-cli-args "Claude"))
      (should-not (eam-notifications-cli-args "Codex")))))
  (let* ((args (eam-notifications-cli-args "Claude"))
         (settings (json-parse-string (cadr args) :object-type 'alist :array-type 'list))
         (hooks (alist-get 'hooks settings)))
    (should (equal (mapcar #'car hooks) '(Stop Notification PermissionRequest)))
    (dolist (entry hooks)
      (let ((hook (car (alist-get 'hooks (cadr entry)))))
        (should (equal (alist-get 'type hook) "command"))
        (should (string-match-p "notify-claude" (alist-get 'command hook)))))))
