;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(defconst eam-review-test-diff
  "diff --git a/한글 파일.py b/한글 파일.py\n--- a/한글 파일.py\n+++ b/한글 파일.py\n@@ -10,3 +10,4 @@\n keep\n-old\n+new\n+extra\n tail\n@@ -30,2 +31,1 @@\n-remove\n remain\n")

(ert-deftest eam-review-hunks-and-new-line-offsets ()
  (with-temp-buffer
    (insert eam-review-test-diff)
    (diff-mode)
    (goto-char (point-min)) (search-forward "+new") (beginning-of-line)
    (let* ((beg (point)) (end (point-max))
           (capture (eam-review--capture beg end))
           (spans (plist-get capture :locations)))
      (should (= (length spans) 2))
      (should (equal (plist-get (car spans) :new-file) "한글 파일.py"))
      (should (= (plist-get (car spans) :new-start) 11))
      (should (= (plist-get (car spans) :new-end) 13))
      (should (= (plist-get (cadr spans) :old-start) 30))
      (should (= (plist-get (cadr spans) :new-start) 31))
      (should (equal (plist-get capture :text) (buffer-substring-no-properties beg end))))))

(ert-deftest eam-review-deletion-and-quoted-path ()
  (should (equal (eam-review--path "\"b/\\355\\225\\234\\352\\270\\200.py\"") "한글.py"))
  (with-temp-buffer
    (insert eam-review-test-diff) (diff-mode)
    (goto-char (point-min)) (search-forward "-remove") (beginning-of-line)
    (let ((span (car (eam-review--locations (point) (line-end-position)))))
      (should (= (plist-get span :old-start) 30))
      (should-not (plist-get span :new-start)))))

(ert-deftest eam-review-limits-and-fences ()
  (with-temp-buffer
    (insert eam-review-test-diff) (diff-mode)
    (let ((eam-review-selection-limit 2))
      (should-error (eam-review--capture (point-min) (point-max)) :type 'user-error)))
  (let ((text (eam-review--render
               '(:text "+```\n+code\n" :locations nil :directory "/tmp/") "한글 의견")))
    (should (string-match-p "````diff\n" text))
    (should (string-match-p "Comment: 한글 의견" text))))

(ert-deftest eam-review-cancel-and-draft-undo ()
  (let* ((output (generate-new-buffer "*review target*"))
         (s (eam-terminal--session :name "Codex" :output output))
         (eam-terminal--sessions (list s)))
    (unwind-protect
        (with-temp-buffer
          (insert eam-review-test-diff) (diff-mode)
          (goto-char (point-min)) (search-forward "+new") (beginning-of-line)
          (let ((beg (point)) (end (line-end-position)))
            (cl-letf (((symbol-function 'use-region-p) (lambda () t))
                      ((symbol-function 'process-send-string) (lambda (&rest _) (ert-fail "Input sent")))
                      ((symbol-function 'read-string) (lambda (&rest _) (signal 'quit nil))))
              (should (eq 'cancelled (condition-case nil (eam-review-selection beg end)
                                      (quit 'cancelled))))
              (should-not (eam-terminal-input s)))
            (cl-letf (((symbol-function 'use-region-p) (lambda () t))
                      ((symbol-function 'process-send-string) (lambda (&rest _) (ert-fail "Input sent")))
                      ((symbol-function 'read-string) (lambda (&rest _) "설명 추가"))
                      ((symbol-function 'completing-read) (lambda (&rest _) (buffer-name output))))
              (eam-review-selection beg end)
              (should (eq (current-buffer) (eam-terminal-input s)))
              (should (string-match-p "설명 추가" (buffer-string)))
              (should-not (eq buffer-undo-list t))
              (undo 1)
              (should (string-empty-p (buffer-string)))))))
      (when (buffer-live-p (eam-terminal-input s)) (kill-buffer (eam-terminal-input s)))
      (kill-buffer output)))

(ert-deftest eam-review-multiple-files-and-header-like-content ()
  (with-temp-buffer
    (insert "--- a/one\n+++ b/one\n@@ -1 +1,2 @@\n-old\n+++ content\n+next\ndiff --git a/two b/two\n--- a/two\n+++ b/two\n@@ -5 +5 @@\n-before\n+after\n")
    (diff-mode)
    (let ((spans (eam-review--locations (point-min) (point-max))))
      (should (= (length spans) 2))
      (should (equal (plist-get (car spans) :new-file) "one"))
      (should (= (plist-get (car spans) :new-end) 2))
      (should (equal (plist-get (cadr spans) :new-file) "two"))
      (should (= (plist-get (cadr spans) :new-start) 5)))))
