;;; session-observation-test.el --- Session observation regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(ert-deftest eam-observation-last-good-survives-worker-errors ()
  (with-temp-buffer
    (eam-usage--accept '((state . "available") (input . 1200)
                         (provider_usage . ((timestamp . 1) (windows . [((minutes . 300) (used . 25))])))))
    (eam-usage--accept nil)
    (should (= 1200 (alist-get 'input eam-usage--snapshot)))
    (should (string-match-p "refresh failed" (eam-usage--provider-text)))
    (should (string-match-p "cached" (eam-usage--provider-text)))
    (eam-usage--accept '((state . "available") (input . 1500)))
    (should-not eam-usage--error)))
(ert-deftest eam-observation-context-comparison-and-unknown-last ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--sort 'context)
    (let ((a '((session . "a") (observation . ((context_used . 400) (context_limit . 1000)))))
          (b '((session . "b") (observation . ((context_percent . 80)))))
          (c '((session . "c"))))
      (should (equal (mapcar #'eam-session-list--path (sort (list c a b) #'eam-session-list--less))
                     '("b" "a" "c")))
      (should (equal (eam-usage--activity-text '((activity . ((state . "executing") (estimated . t))))) "executing~")))))
(ert-deftest eam-quick-uses-configured-directory-without-name-or-project-prompt ()
  (let* ((root (make-temp-file "eam-quick-test" t)) (eam-quick-directory (expand-file-name "한글" root)) called)
    (unwind-protect
        (cl-letf (((symbol-function 'eam--read-provider) (lambda () "Codex"))
                  ((symbol-function 'read-directory-name) (lambda (&rest _) (ert-fail "Unexpected project prompt")))
                  ((symbol-function 'eam-persistent--start)
                   (lambda (provider directory args name temporary)
                     (should (equal provider "Codex"))
                     (should (equal directory eam-quick-directory))
                     (should (file-directory-p directory))
                     (should-not args) (should (equal name "quick")) (should temporary)
                     (setq called t))))
          (call-interactively #'eam-quick) (should called))
      (delete-directory root t))))
(ert-deftest eam-note-undo-private-save-survives-exit ()
  (let* ((root (make-temp-file "eam-note-test" t)) (buffer (generate-new-buffer " *eam-note-test*")) saved)
    (unwind-protect
        (with-current-buffer buffer
          (eam-note-mode) (setq eam-note--directory root)
          (insert "한글 메모") (undo-boundary) (insert " 수정")
          (should (listp buffer-undo-list))
          (should-not buffer-file-name) (should-not buffer-auto-save-file-name)
          (cl-letf (((symbol-function 'eam-persistent--call)
                     (lambda (action q) (should (equal action "note-save"))
                       (setq saved (alist-get 'text q)) nil)))
            (eam-note--save))
          (should (equal saved "한글 메모 수정")) (should-not (buffer-modified-p))
          (with-temp-file (expand-file-name "session.json" root) (insert "{\"stopped\":true}"))
          (should (buffer-live-p buffer))
          (insert " retained after exit")
          (should (buffer-modified-p)))
      (when (buffer-live-p buffer) (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))
      (delete-directory root t))))
(ert-deftest eam-cycle-replaces-selected-window-without-touching-other-window ()
  (save-window-excursion
    (let ((a (generate-new-buffer " *eam-cycle-a*")) (b (generate-new-buffer " *eam-cycle-b*"))
          (other (generate-new-buffer " *eam-cycle-other*")))
      (unwind-protect
          (progn
            (delete-other-windows)
            (switch-to-buffer a)
            (let ((second (split-window-right)))
              (set-window-buffer second other)
              (with-current-buffer a
                (setq eam-terminal--current (eam-terminal--session :output a)
                      eam-terminal-persistent-directory "/tmp/a"))
              (let ((entries '(((session . "/tmp/a") (created_at . 1) (attached_clients . 1))
                               ((session . "/tmp/b") (created_at . 2) (attached_clients . 1)))))
                (cl-letf (((symbol-function 'eam-app--live-inventory) (lambda () `((sessions . ,entries))))
                          ((symbol-function 'eam-session-list--buffer)
                           (lambda (e) (if (equal (alist-get 'session e) "/tmp/a") a b)))
                          ((symbol-function 'eam-session-list--ack) #'ignore))
                  (let ((selected (selected-window))
                        (switch-to-buffer-obey-display-actions t)
                        (display-buffer-alist '(("eam-cycle" display-buffer-pop-up-window))))
                    (eam-next-session)
                    (should (eq (selected-window) selected))
                    (should (eq (window-buffer selected) b))
                    (should (eq (window-buffer second) other))
                    (should (= 2 (length (window-list)))))))))
        (mapc #'kill-buffer (list a b other))))))

(ert-deftest eam-persist-updates-local-lifecycle-only-after-confirmation ()
  (with-temp-buffer
    (setq-local eam-terminal-persistent-directory "/tmp/eam-keep-test")
    (setq-local eam-terminal-temporary t)
    (cl-letf (((symbol-function 'eam-persistent--call)
               (lambda (_action _request) (error "Old daemon"))))
      (should-error (eam-persist))
      (should eam-terminal-temporary))
    (cl-letf (((symbol-function 'eam-persistent--call)
               (lambda (action request)
                 (should (equal action "persist"))
                 (should (equal (alist-get 'session request) eam-terminal-persistent-directory))
                 '((temporary . :false)))))
      (eam-persist)
      (should-not eam-terminal-temporary))))

(ert-deftest eam-note-native-save-pins-identity-and-keeps-conflicting-edits ()
  (let* ((root (make-temp-file "eam-note-native-" t))
         (session (expand-file-name "session" root)))
    (unwind-protect
        (progn
          (make-directory session)
          (set-file-modes session #o700)
          (with-temp-file (expand-file-name "session.json" session)
            (insert (json-encode `((version . 1) (id . "00000000000000000000000000000000")
                                  (provider . "Codex") (auth_root . ,root) (stopped . t)))))
          (with-temp-buffer
            (eam-note-mode)
            (setq eam-note--directory session)
            (insert "첫 메모")
            (eam-note--save)
            (should-not eam-note--identity)
            (with-temp-file (expand-file-name "telemetry.json" session)
              (insert "{\"id\":\"conversation-one\"}"))
            (insert " 수정")
            (eam-note--save)
            (should eam-note--identity)
            (eam-persistent--call "note-save"
              `((session . ,session) (identity . ,eam-note--identity) (text . "다른 편집기")))
            (insert " 충돌")
            (should-error (eam-note--save))
            (should (buffer-modified-p))
            (should (string-suffix-p "충돌" (buffer-string)))))
      (delete-directory root t))))

(ert-deftest eam-cycle-preserves-scrollback-and-live-follow ()
  (save-window-excursion
    (let ((a (generate-new-buffer " *eam-scroll-a*"))
          (b (generate-new-buffer " *eam-scroll-b*")))
      (unwind-protect
          (progn
            (delete-other-windows)
            (dolist (buffer (list a b))
              (with-current-buffer buffer
                (ghostel-mode)
                (let ((inhibit-read-only t))
                  (dotimes (n 300) (insert (format "line %d\n" n))))
                (setq-local ghostel--input-mode 'semi-char)
                (setq-local eam-terminal--current (eam-terminal--session :output buffer))
                (setq-local eam-terminal-persistent-directory (if (eq buffer a) "/tmp/a" "/tmp/b"))))
            (switch-to-buffer a)
            (goto-char (point-min)) (forward-line 35)
            (set-window-start (selected-window) (point) t)
            (forward-line 4)
            (let ((start (window-start)) (saved-point (point)) (anchors 0)
                  (entries '(((session . "/tmp/a") (created_at . 1) (attached_clients . 1))
                             ((session . "/tmp/b") (created_at . 2) (attached_clients . 1)))))
              (cl-letf (((symbol-function 'eam-app--live-inventory) (lambda () `((sessions . ,entries))))
                        ((symbol-function 'eam-session-list--buffer)
                         (lambda (e) (if (equal (alist-get 'session e) "/tmp/a") a b)))
                        ((symbol-function 'eam-session-list--ack) #'ignore)
                        ((symbol-function 'ghostel--anchor-window)
                         (lambda (&rest _) (cl-incf anchors) (goto-char (point-max)))))
                (eam-next-session)
                (eam-previous-session)
                (eam-terminal--window-buffer-change (selected-window))
                (should (eq (current-buffer) a))
                (should (= (window-start) start))
                (should (= (point) saved-point))
                (should (= anchors 0))
                ;; Live-edge windows should still follow on redisplay.
                (goto-char (point-max))
                (set-window-start (selected-window) (point-max) t)
                (eam-terminal--window-buffer-change (selected-window))
                (should (= anchors 1)))))
        (dolist (buffer (list a b))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer))))))
