;;; session-list-test.el --- Session management regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(defun eam-list-test-entry (id directory name activity &optional unread)
  (copy-tree `((session . ,(concat "/tmp/" id)) (directory . ,directory) (name . ,name)
    (provider . "Codex") (attached_clients . 0) (created_at . 10)
    (last_input_at . ,activity) (last_output_at . 0)
    (notifications . ((seq . 2) (read_seq . ,(if unread 0 2)) (unread . ,unread))))))

(ert-deftest eam-list-prefill-and-name-flow ()
  (let ((default-directory "/tmp/한글 프로젝트/") (insert-default-directory nil) calls)
    (cl-letf (((symbol-function 'eam--read-provider) (lambda () "Codex"))
              ((symbol-function 'read-directory-name)
               (lambda (_ dir default mustmatch &optional initial &rest _)
                 (should (equal dir default-directory))
                 (should (equal default default-directory))
                 (should-not initial) (should-not mustmatch) default))
              ((symbol-function 'file-directory-p) (lambda (_path) t))
              ((symbol-function 'read-string) (lambda (&rest _) "새 작업"))
              ((symbol-function 'eam-persistent--start)
               (lambda (provider directory args &optional name)
                 (push (list provider directory args name) calls) (eam-terminal--session))))
      (call-interactively #'eam-new)
      (call-interactively #'eam-resume)
      (should (equal (reverse calls)
                     '(("Codex" "/tmp/한글 프로젝트/" nil "새 작업")
                       ("Codex" "/tmp/한글 프로젝트/" ("resume") "새 작업")))))))

(ert-deftest eam-list-groups-sorts-filter-and-selection ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--entries
          (list (eam-list-test-entry "a" "/tmp/project/" "같은 이름" 20)
                (eam-list-test-entry "b" "/tmp/project" "같은 이름" 30)
                (eam-list-test-entry "c" "/tmp/other" "다른 이름" 40 t))
          eam-session-list--sort 'activity eam-session-list--group t)
    (eam-session-list--render)
    (should (eq buffer-undo-list t))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/c"))
    (should (= 1 (how-many "^  /tmp/project  ·  2 sessions$" (point-min) (point-max))))
    (dolist (order '(activity created directory name provider state unread))
      (setq eam-session-list--sort order)
      (eam-session-list--render "/tmp/b")
      (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/b")))
    (setq eam-session-list--sort 'unread)
    (should (equal (mapcar #'eam-session-list--path
                          (sort (copy-sequence eam-session-list--entries) #'eam-session-list--less))
                   '("/tmp/c" "/tmp/b" "/tmp/a")))
    (should (string-match-p "NEW" (buffer-string)))
    (should (string-match-p "read" (buffer-string)))
    (setf (alist-get 'attached_clients (car eam-session-list--entries)) 1)
    (setq eam-session-list--detached t)
    (eam-session-list--render)
    (should-not (string-match-p "  a\n" (buffer-string)))))

(ert-deftest eam-list-provider-filter-composes-and-survives-refresh ()
  (with-temp-buffer
    (eam-session-list-mode)
    (let ((codex (eam-list-test-entry "codex" "/tmp/shared" "Codex task" 10))
          (claude (eam-list-test-entry "claude" "/tmp/shared" "Claude task" 20))
          (choice "Claude"))
      (setf (alist-get 'provider claude) "Claude"
            (alist-get 'attached_clients claude) 1)
      (setq eam-session-list--entries (list codex claude)
            eam-session-list--sort 'activity eam-session-list--group t)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt candidates _predicate require-match &rest _)
                   (should require-match)
                   (should (equal candidates '("All" "Codex" "Claude")))
                   choice))
                ((symbol-function 'eam-app--live-inventory)
                 (lambda (&rest _) `((sessions . (,codex ,claude))))))
        (call-interactively (key-binding (kbd "v")))
        (should (string-match-p "provider: Claude" (buffer-string)))
        (should (equal (eam-session-list--at-point) claude))
        (should-not (string-match-p "Codex task" (buffer-string)))
        (should (string-match-p "1 sessions" (buffer-string)))
        (eam-session-list--refresh)
        (should (equal eam-session-list--provider "Claude"))
        (should (equal (eam-session-list--at-point) claude))
        ;; An attached Claude is excluded by the independent detached filter.
        (call-interactively (key-binding (kbd "f")))
        (should (string-match-p "No sessions in this view" (buffer-string)))
        (should-not (eam-session-list--at-point))
        (setq choice "Codex")
        (call-interactively (key-binding (kbd "v")))
        (should (equal (eam-session-list--at-point) codex))
        (should-not (string-match-p "Claude task" (buffer-string)))
        (setq choice "All")
        (call-interactively (key-binding (kbd "v")))
        (should-not eam-session-list--provider)
        (should eam-session-list--detached)
        (call-interactively (key-binding (kbd "f")))
        (should (string-match-p "Codex task" (buffer-string)))
        (should (string-match-p "Claude task" (buffer-string)))
        (should (= 2 (length eam-session-list--entries)))))))

(ert-deftest eam-list-open-does-not-acknowledge-failed-attachment ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--entries (list (eam-list-test-entry "a" "/tmp" "" 0 t))
          eam-session-list--sort 'activity)
    (eam-session-list--render)
    (let ((eam-terminal--sessions nil))
      (cl-letf (((symbol-function 'eam-attach) (lambda (&rest _) (user-error "Unavailable")))
                ((symbol-function 'eam-notifications--acknowledge)
                 (lambda (&rest _) (ert-fail "Read without successful visit"))))
        (should-error (eam-session-list--open) :type 'user-error)))))

(ert-deftest eam-list-acknowledges-snapshot-only ()
  (let* ((entry (eam-list-test-entry "a" "/tmp" "" 0 t))
         (old (eam-notice--make :session "/tmp/a" :sequence 2))
         (new (eam-notice--make :session "/tmp/a" :sequence 3))
         (eam-notifications--entries (list new old)))
    (cl-letf (((symbol-function 'eam-persistent--call)
               (lambda (op request)
                 (should (equal op "acknowledge"))
                 (should (= (alist-get 'seq request) 2))
                 '((seq . 3) (read_seq . 2) (unread . t)))))
      (eam-session-list--ack entry)
      (should (eam-notice-read old))
      (should-not (eam-notice-read new)))))

(ert-deftest eam-list-rename-keeps-provider-identity-and-draft-undo ()
  (let* ((out (generate-new-buffer " *eam-name-output*"))
         (draft (generate-new-buffer " *eam-name-draft*"))
         (s (eam-terminal--session :name "Codex" :directory "/tmp/project/"
                                   :input draft :output out :resume-id "same-id"))
         (eam-terminal--sessions (list s)))
    (unwind-protect
        (progn
          (with-current-buffer out (setq-local eam-terminal-persistent-directory "/tmp/session"))
          (with-current-buffer draft
            (setq-local eam-terminal--current s)
            (buffer-enable-undo) (insert "수정 중")
            (let ((undo buffer-undo-list))
              (cl-letf (((symbol-function 'eam-persistent--call)
                         (lambda (op q)
                           (should (equal op "rename"))
                           (should (equal (alist-get 'session q) "/tmp/session"))
                           '((name . "이름 변경")))))
                (eam-rename "이름 변경"))
              (should (eq undo buffer-undo-list))
              (should (buffer-modified-p))
              (should (equal (buffer-string) "수정 중"))))
          (should (equal (eam-terminal-name s) "Codex"))
          (should (equal (eam-terminal-resume-id s) "same-id"))
          (should (string-match-p "이름 변경" (buffer-name out)))
          (should (string-match-p "이름 변경" (buffer-name draft))))
      (kill-buffer out) (with-current-buffer draft (set-buffer-modified-p nil)) (kill-buffer draft))))

(ert-deftest eam-list-bounded-render-256-sessions ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--sort 'activity eam-session-list--group t
          eam-session-list--entries
          (cl-loop for i below 256 collect
                   (eam-list-test-entry (format "session-%d" i)
                                        (format "/tmp/project-%d/" (% i 32))
                                        (make-string 128 ?한) i)))
    (let ((started (float-time)))
      (dotimes (_ 10) (eam-session-list--render))
      (message "Session list: 256 sessions, 32 groups, 10 renders %.3fs, %d chars"
               (- (float-time) started) (buffer-size)))
    (should (< (buffer-size) 100000))
    (should (eq buffer-undo-list t))))

(ert-deftest eam-list-notice-restart-restores-read-state ()
  (let* ((dir (make-temp-file "eam-notice-read-" t))
         (file (expand-file-name "events.jsonl" dir))
         (buffer (generate-new-buffer " *eam-notice-restart*"))
         (eam-notifications--entries nil)
         (eam-notification-desktop nil))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "{\"version\":1,\"seq\":1,\"title\":\"완료\",\"body\":\"첫 응답\"}\n")
            (insert "{\"version\":1,\"seq\":2,\"title\":\"완료\",\"body\":\"새 응답\"}\n"))
          (with-temp-file (expand-file-name "notification-read.json" dir)
            (insert "{\"seq\":1}"))
          (let ((reader (eai-event-reader--create file buffer)))
            (eai-event-reader-poll reader)
            (should (= (length eam-notifications--entries) 2))
            (should-not (eam-notice-read (car eam-notifications--entries)))
            (should (eam-notice-read (cadr eam-notifications--entries)))
            (should (equal (eam-notice-session (car eam-notifications--entries)) dir))
            (eai-event-reader-poll reader)
            (should (= (length eam-notifications--entries) 2))))
      (kill-buffer buffer) (delete-directory dir t))))

(ert-deftest eam-list-navigation-skips-groups-and-stops-at-edges ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--entries
          (list (eam-list-test-entry "a" "/tmp/one" "첫째" 30)
                (eam-list-test-entry "b" "/tmp/two" "둘째" 20))
          eam-session-list--sort 'activity eam-session-list--group t)
    (eam-session-list--render)
    (call-interactively (key-binding (kbd "p")))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/a"))
    (call-interactively (key-binding (kbd "n")))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/b"))
    (call-interactively (key-binding (kbd "n")))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/b"))
    (call-interactively (key-binding (kbd "p")))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/a"))))

(ert-deftest eam-list-cycle-is-stable-wraps-and-skips-detached ()
  (with-temp-buffer
    (let* ((a (eam-list-test-entry "a" "/tmp" "a" 900))
           (b (eam-list-test-entry "b" "/tmp" "b" 100))
           (c (eam-list-test-entry "c" "/tmp" "c" 500))
           (external (eam-list-test-entry "external" "/tmp" "external" 0))
           visits)
      (setf (alist-get 'created_at a) 1 (alist-get 'created_at b) 2
            (alist-get 'created_at c) 3 (alist-get 'attached_clients external) 1
            (alist-get 'attached_clients a) 1 (alist-get 'attached_clients b) 1)
      (setq-local eam-terminal--current (eam-terminal--session :output (current-buffer))
                  eam-terminal-persistent-directory "/tmp/a")
      (cl-letf (((symbol-function 'eam-app--live-inventory)
                 (lambda () `((sessions . ,(list c external a b)))))
                ((symbol-function 'eam-session-list--buffer)
                 (lambda (entry) (when (memq entry (list a b)) (current-buffer))))
                ((symbol-function 'pop-to-buffer) (lambda (&rest _) (ert-fail "Cycle must not split windows")))
                ((symbol-function 'switch-to-buffer) #'ignore)
                ((symbol-function 'eam-attach) (lambda (&rest _) (ert-fail "Unexpected attach")))
                ((symbol-function 'eam-session-list--ack)
                 (lambda (entry) (setq eam-terminal-persistent-directory (eam-session-list--path entry))
                   (push eam-terminal-persistent-directory visits))))
        (call-interactively (lookup-key eam-terminal-controls-mode-map (kbd "C-M-n")))
        (eam-next-session)
        (eam-next-session)
        (call-interactively (lookup-key eam-terminal-controls-mode-map (kbd "C-M-p")))
        (should (equal (reverse visits) '("/tmp/b" "/tmp/a" "/tmp/b" "/tmp/a")))))))

(ert-deftest eam-list-interrupted-resumes-instead-of-attaching ()
  (let ((entry '((session . "/tmp/lost") (state . "interrupted")
                 (provider . "Codex") (directory . "/tmp/") (name . "saved name")
                 (auth_root . "/tmp/codex-profile")
                 (resume_id . "11111111-2222-3333-4444-555555555555"))) calls)
    (should (equal (eam-session-list--state entry) "interrupted"))
    (cl-letf (((symbol-function 'eam-persistent--start)
               (lambda (provider directory args name temporary source)
                 (push (list provider directory args name temporary source (getenv "CODEX_HOME")) calls)))
              ((symbol-function 'eam-attach) (lambda (&rest _) (ert-fail "Must resume, not attach")))
              ((symbol-function 'eam-session-list--ack) #'ignore))
      (eam-session-list--visit entry)
      (should (equal (car calls)
                     '("Codex" "/tmp/" ("resume" "11111111-2222-3333-4444-555555555555")
                       "saved name" nil "/tmp/lost" "/tmp/codex-profile")))
      (setf (alist-get 'resume_id entry) nil)
      (eam-session-list--visit entry)
      (should (equal (nth 2 (car calls)) '("resume"))))))

(ert-deftest eam-project-directory-create-before-new-and-resume ()
  (dolist (command '(eam-new eam-resume))
    (let* ((root (make-temp-file "eam-project-create-" t))
           (path (expand-file-name "새 프로젝트/nested" root)) confirmed started)
      (unwind-protect
          (cl-letf (((symbol-function 'eam--read-provider) (lambda () "Codex"))
                    ((symbol-function 'read-directory-name) (lambda (&rest _) path))
                    ((symbol-function 'yes-or-no-p)
                     (lambda (prompt) (should (string-match-p (regexp-quote path) prompt))
                       (should-not (file-exists-p path)) (setq confirmed t)))
                    ((symbol-function 'read-string) (lambda (&rest _) ""))
                    ((symbol-function 'eam-persistent--start)
                     (lambda (_provider directory &rest _)
                       (should confirmed) (should (file-directory-p directory))
                       (setq started t) (eam-terminal--session))))
            (call-interactively command)
            (should started))
        (delete-directory root t)))))

(ert-deftest eam-project-directory-decline-and-file-conflict-do-not-start ()
  (let* ((root (make-temp-file "eam-project-decline-" t))
         (path (expand-file-name "missing" root)) (prompts 0))
    (unwind-protect
        (cl-letf (((symbol-function 'eam--read-provider) (lambda () "Codex"))
                  ((symbol-function 'read-directory-name) (lambda (&rest _) path))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) (cl-incf prompts) nil))
                  ((symbol-function 'read-string) (lambda (&rest _) (ert-fail "Name requested after cancellation")))
                  ((symbol-function 'eam-persistent--start) (lambda (&rest _) (ert-fail "Unexpected CLI start"))))
          (should-error (call-interactively #'eam-new) :type 'user-error)
          (should (= prompts 1))
          (should-not (file-exists-p path))
          (with-temp-file path (insert "keep"))
          (setq path (file-name-as-directory path))
          (should-error (call-interactively #'eam-resume) :type 'user-error)
          (should (= prompts 1)))
      (delete-directory root t))))

(ert-deftest eam-list-remote-state-follows-live-attachment ()
  (should (equal (eam-session-list--state '((state . "running") (attached_clients . 1) (remote . t))) "remote"))
  (should (equal (eam-session-list--state '((state . "running") (attached_clients . 0) (remote . t))) "detached"))
  (should (equal (eam-session-list--state '((state . "running") (attached_clients . 1))) "attached"))
  (should (equal (eam-session-list--state '((state . "interrupted") (remote . t))) "interrupted")))
