;;; terminal-stream-soak.el --- Timed real-PTY output, no AI -*- lexical-binding: t; -*-
(require 'eam-terminal)
(defvar ai-stream-dir (getenv "EMACS_AI_STREAM_DIR"))
(defvar ai-stream-seconds (string-to-number (or (getenv "EMACS_AI_STREAM_SECONDS") "600")))
(defvar ai-stream-sessions nil)
(defvar ai-stream-samples nil)
(defvar ai-stream-new (float-time))
(defun ai-stream-rss ()
  (with-temp-buffer
    (unless (zerop (call-process "ps" nil t nil "-o" "rss=" "-p" (number-to-string (emacs-pid))))
      (error "RSS query failed"))
    (string-to-number (buffer-string))))
(defun ai-stream-sample ()
  (let (rows)
    (dolist (entry ai-stream-sessions)
      (let* ((s (cdr entry)) (alive (process-live-p (eam-terminal-process s)))
             (tag (format "한글-ping-%d-%d" (car entry) (length ai-stream-samples))))
        (set-window-buffer (selected-window) (eam-terminal-output s))
        (ghostel--redraw-now (eam-terminal-output s) t)
        (let ((sent (float-time)))
          (when alive
            (with-current-buffer (eam-terminal--ensure-draft s)
              (erase-buffer) (insert tag) (eam-paste)))
          (push `((session . ,(car entry)) (tag . ,tag) (sent_at . ,sent)
                  (alive . ,(if alive t :json-false))
                  (raw_file . ,(eam-terminal-file s))
                  (raw_bytes . ,(file-attribute-size (file-attributes (eam-terminal-file s))))
                  (output_chars . ,(with-current-buffer (eam-terminal-output s) (buffer-size)))
                  (output_undo_disabled . ,(with-current-buffer (eam-terminal-output s) (eq buffer-undo-list t)))
                  (input_undo_enabled . ,(not (with-current-buffer (eam-terminal--ensure-draft s) (eq buffer-undo-list t))))) rows))))
    (push `((elapsed_s . ,(- (float-time) ai-stream-new)) (rss_kib . ,(ai-stream-rss))
            (sessions . ,(vconcat (nreverse rows)))) ai-stream-samples)
    (with-temp-file (expand-file-name "samples.json" ai-stream-dir)
      (insert (json-encode (vconcat (reverse ai-stream-samples)))))))
(defun ai-stream-cleanup-sample (phase)
  "Measure real footprint at each cleanup boundary while Emacs is alive."
  (let* ((file (expand-file-name (concat "cleanup-" phase ".jsonl") ai-stream-dir))
         (status (call-process (eam--executable "python3") nil nil nil
                               (expand-file-name "tests/process-footprint.py")
                               (number-to-string (emacs-pid)) file
                               "--duration" ".1" "--interval" ".1")))
    (unless (zerop status) (error "Cleanup memory measurement failed: %s" phase))
    (let ((usage (with-temp-buffer
                   (insert-file-contents file)
                   (json-parse-string (buffer-string) :object-type 'alist))))
      (with-temp-buffer
        (insert (json-encode
                 `((phase . ,phase) (elapsed . ,(- (float-time) ai-stream-new))
                   (usage . ,usage) (buffers . ,(length (buffer-list)))
                   (process_objects . ,(length (process-list)))
                   (sessions . ,(length eam-terminal--sessions))
                   (timers . ,(length timer-list)))))
        (insert "\n")
        (write-region (point-min) (point-max)
                      (expand-file-name "cleanup.jsonl" ai-stream-dir) t 'silent)))))
(make-directory ai-stream-dir t)
(set-frame-size (selected-frame) 120 50)
(delete-other-windows)
(unwind-protect
    (progn
      (dotimes (i 2)
        (let ((dir (expand-file-name (number-to-string i) ai-stream-dir)))
          (make-directory dir t)
          (push (cons i (eam-terminal-start
                         (format "stream-%d" i) (eam--executable "python3")
                         (list (expand-file-name "tests/stream-fixture.py") dir (number-to-string ai-stream-seconds))
                         default-directory)) ai-stream-sessions)))
      (let ((next (+ (float-time) 2)) (deadline (+ (float-time) ai-stream-seconds 30)))
        (while (and (cl-some (lambda (entry) (process-live-p (eam-terminal-process (cdr entry)))) ai-stream-sessions)
                    (< (float-time) deadline))
          (accept-process-output nil .02)
          (when (> (float-time) next)
            (ai-stream-sample)
            (setq next (+ (float-time) 30))))
        (when (cl-some (lambda (entry) (process-live-p (eam-terminal-process (cdr entry)))) ai-stream-sessions)
          (error "Output producer exceeded deadline")))
      (ai-stream-sample)
      ;; Exercise bounded archive pages after the stream has completed.
      (let ((eam-buffer-limit 4096) pages)
        (dolist (entry ai-stream-sessions)
          (let* ((s (cdr entry)) (history (eam--create (eam-terminal-file s))))
            (unwind-protect
                (with-current-buffer (eam-session-output history)
                  (dotimes (_ 8)
                    (eam-history-previous-page)
                    (unless (<= (buffer-size) 4096) (error "History page exceeded cap"))
                    (push (buffer-size) pages)))
              (with-current-buffer (eam-session-output history) (eam-detach)))))
        (with-temp-file (expand-file-name "history-pages.json" ai-stream-dir)
          (insert (json-encode (vconcat pages))))))
  (unwind-protect
      (progn
        (unwind-protect
            (ai-stream-cleanup-sample "before-close")
          (dolist (entry ai-stream-sessions)
            (when (buffer-live-p (eam-terminal-output (cdr entry)))
              (with-current-buffer (eam-terminal-output (cdr entry))
                (eam-detach))))
          (setq ai-stream-sessions nil))
        (ai-stream-cleanup-sample "closed")
        (garbage-collect)
        (accept-process-output nil .1)
        (garbage-collect)
        (ai-stream-cleanup-sample "closed-gc"))
    (server-force-delete)))
