;;; terminal-lifecycle-probe.el --- Inspect owned child lifetimes -*- lexical-binding: t; -*-
(require 'eam-terminal)
(let* ((dir (getenv "EMACS_AI_LIFECYCLE_DIR"))
       (action (getenv "EMACS_AI_LIFECYCLE_ACTION"))
       (s (eam-terminal-start
           "lifecycle" (eam--executable "python3")
           (list (expand-file-name (or (getenv "EMACS_AI_LIFECYCLE_FIXTURE")
                                      "tests/lifecycle-fixture.py")) dir) default-directory))
       (end (+ (float-time) 10)))
  (while (and (not (file-exists-p (expand-file-name "pids.json" dir))) (< (float-time) end))
    (accept-process-output nil .05))
  (unless (file-exists-p (expand-file-name "pids.json" dir)) (error "Fixture not ready"))
  (with-temp-file (expand-file-name "emacs.pid" dir) (insert (number-to-string (emacs-pid))))
  (when (getenv "EMACS_AI_LIFECYCLE_GATE")
    (let ((deadline (+ (float-time) 45)))
      (while (and (not (file-exists-p (expand-file-name "go" dir)))
                  (< (float-time) deadline))
        (accept-process-output nil .05))
      (unless (file-exists-p (expand-file-name "go" dir)) (error "Supervisor gate timeout"))))
  (let ((end (+ (float-time) .5)))
    (while (< (float-time) end) (accept-process-output nil .05)))
  (pcase action
    ("close" (with-current-buffer (eam-terminal-output s) (eam-detach)))
    ("cli-kill" (signal-process (process-id (eam-terminal-process s)) 9))
    ("emacs-exit" (kill-emacs 0))
    ("emacs-kill" (signal-process (emacs-pid) 9)))
  (let ((end (+ (float-time) 2)))
    (while (< (float-time) end) (accept-process-output nil .05)))
  (when (buffer-live-p (eam-terminal-output s))
    (with-current-buffer (eam-terminal-output s) (eam-detach)))
  (server-force-delete))
