;;; terminal-churn.el --- Repeated real PTY sessions, no AI -*- lexical-binding: t; -*-
(require 'eam-terminal)
(defvar ai-churn-dir (getenv "EMACS_AI_CHURN_DIR"))
(defvar ai-churn-samples nil)
(defun ai-churn-wait (predicate)
  (let ((deadline (+ (float-time) 8)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil .01))
    (unless (funcall predicate) (error "Churn fixture timeout"))))
(defun ai-churn-sample (count)
  (garbage-collect)
  (let ((rss (with-temp-buffer
               (unless (zerop (call-process "ps" nil t nil "-o" "rss=" "-p"
                                            (number-to-string (emacs-pid))))
                 (error "RSS query failed"))
               (string-to-number (buffer-string)))))
    (push `((completed . ,count) (rss_kib . ,rss)
            (registered_sessions . ,(length eam-terminal--sessions))
            (buffer_count . ,(length (buffer-list)))
            (live_process_count . ,(cl-count-if #'process-live-p (process-list)))
            (timer_count . ,(length timer-list))) ai-churn-samples)
    (with-temp-file (expand-file-name "samples.json" ai-churn-dir)
      (insert (json-encode (vconcat (reverse ai-churn-samples)))))))
(let ((eam-directory ai-churn-dir)
      (started (float-time))
      sessions)
  (when (file-exists-p ai-churn-dir) (error "Use a fresh churn output directory"))
  (make-directory ai-churn-dir t)
  (unwind-protect
      (progn
        (dotimes (round 50)
          (dotimes (i 4)
            (push (eam-terminal-start
                   (format "churn-%d-%d" round i) (eam--executable "python3")
                   (list (expand-file-name "tests/terminal-fixture.py")
                         (expand-file-name (format "receipt-%d-%d.jsonl" round i) ai-churn-dir))
                   default-directory) sessions))
          (dolist (s sessions)
            (ai-churn-wait
             (lambda () (with-current-buffer (eam-terminal-output s)
                          (ghostel--mode-enabled ghostel--term 2004))))
            (with-current-buffer (eam-terminal--ensure-draft s)
              (insert "반복 생성🙂\n둘째 줄")
              (eam-paste)
              (eam-terminal-key "return"))
            (ai-churn-wait
             (lambda () (with-temp-buffer
                          (insert-file-contents (eam-terminal-file s))
                          (search-forward "ENTER" nil t))))
            ;; Closing an optional draft must not stop its CLI.
            (with-current-buffer (eam-terminal-input s)
              (set-buffer-modified-p nil) (kill-buffer))
            (unless (process-live-p (eam-terminal-process s))
              (error "Draft close stopped CLI"))
            (pcase (% round 3)
              (0 (with-current-buffer (eam-terminal-output s) (eam-detach)))
              (1 (kill-buffer (eam-terminal-output s)))
              (2 (with-current-buffer (eam-terminal-output s) (eam-terminal-key "c" "ctrl"))
                 (ai-churn-wait (lambda () (not (process-live-p (eam-terminal-process s)))))
                 (unless (buffer-live-p (eam-terminal-output s))
                   (error "Native exit lost output"))
                 (with-current-buffer (eam-terminal-output s) (eam-detach))))
            (when (or (process-live-p (eam-terminal-process s))
                      (buffer-live-p (eam-terminal-output s))
                      (buffer-live-p (eam-terminal-input s)))
              (error "Session resources remain after close")))
          (setq sessions nil)
          (when eam-terminal--sessions (error "Session registry leak"))
          (accept-process-output nil .02)
          (when (zerop (% (1+ round) 5)) (ai-churn-sample (* 4 (1+ round)))))
        (with-temp-file (expand-file-name "result.json" ai-churn-dir)
          (insert (json-encode `((completed . 200) (concurrent . 4)
                                 (elapsed_seconds . ,(- (float-time) started))
                                 (ai_requests . 0) (gui . :json-false)
                                 (all_close_assertions_passed . t))))))
    (dolist (s sessions)
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach))))
    (server-force-delete)))
