;;; terminal-test.el -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(setq eam-record-terminal t)
(defconst eam-terminal-test-root
  (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
(defun eam-terminal-test-wait (predicate)
  (let ((end (+ (float-time) 8)))
    (while (and (not (funcall predicate)) (< (float-time) end)) (accept-process-output nil .02))
    (should (funcall predicate))))
(ert-deftest eam-terminal-editor-server-failure-cleans-fallback ()
  "An unavailable local editor server must not leak its temporary directory."
  (let ((eam-directory (concat "/tmp/" (make-string 120 ?x)))
        (server-process nil)
        (server-name nil)
        (server-socket-dir nil)
        (eam-terminal--temporary-socket-directory nil)
        (kill-emacs-hook nil)
        directory)
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'server-start)
                     (lambda ()
                       (setq directory server-socket-dir)
                       (should (file-directory-p directory))
                       (should (= (logand (file-modes directory) #o777) #o700))
                       (signal 'file-error '("Local socket unavailable")))))
            (should (equal (should-error (eam-terminal--editor-command)
                                         :type 'file-error)
                           '(file-error "Local socket unavailable"))))
          (should directory)
          (should-not (file-exists-p directory))
          (should-not eam-terminal--temporary-socket-directory)
          (should-not kill-emacs-hook))
      (when (and directory (file-directory-p directory))
        (delete-directory directory)))))
(ert-deftest eam-terminal-archive-survives-close ()
  "Reopen persisted ANSI after closing the PTY, with bounded reads and pages."
  (let* ((eam-directory (make-temp-file "ai-archive-" t))
         (eam-buffer-limit 128)
         (eam-terminal-redraw-delay 0.033)
         (coding-system-for-read 'utf-8-unix)
         (s (eam-terminal-start
             "archive" (eam--executable "python3")
             (list (expand-file-name "tests/terminal-fixture.py" eam-terminal-test-root)
                   (expand-file-name "received.jsonl" eam-directory))
             eam-directory))
         (file (eam-terminal-file s))
         (reader (symbol-function 'insert-file-contents-literally))
         viewer original reads pages)
    (unwind-protect
        (progn
          (eam-terminal-test-wait
           (lambda () (with-current-buffer (eam-terminal-output s)
                        (ghostel--mode-enabled ghostel--term 2004))))
          (with-current-buffer (eam-terminal-output s)
            (should (local-variable-p 'ghostel-timer-delay))
            (should (= ghostel-timer-delay 0.033)))
          ;; Exercise the recording filter with control sequences and UTF-8.
          (eam-terminal--filter
           s (eam-terminal-process s)
           (encode-coding-string
            (apply #'concat (make-list 80 "\e[31m한글🙂\e[0m 코드\r\n")) 'utf-8-unix))
          (with-current-buffer (eam-terminal-output s) (eam-detach))
          (should-not (process-live-p (eam-terminal-process s)))
          (should-not (memq s eam-terminal--sessions))
          (setq original (with-temp-buffer
                           (insert-file-contents file) (buffer-string)))
          (cl-letf (((symbol-function 'insert-file-contents-literally)
                     (lambda (name &optional visit start end replace)
                       (when (equal name file)
                         (should (integerp start))
                         (should (integerp end))
                         (should (<= (- end start) eam-buffer-limit))
                         (push (cons start end) reads))
                       (funcall reader name visit start end replace))))
            (eam-history-open file)
            (setq viewer eam--current)
            (setq-local eam-history-hide-colors nil)
            (should (<= (buffer-size) eam-buffer-limit))
            (eam-history-previous-page)
            (push (buffer-string) pages)
            (while (> (car (eam-session-cursor viewer)) 0)
              (eam-history-previous-page)
              (should (<= (buffer-size) eam-buffer-limit))
              (should (eq buffer-undo-list t))
              (push (buffer-string) pages))
            (should (equal (apply #'concat pages) original))
            (should (> (length reads) 10))
            (should-not (eam-session-process viewer))
            (should-not (eam-session-timer viewer)))
          (should (equal original (with-temp-buffer
                                   (insert-file-contents file) (buffer-string)))))
      (when (and viewer (buffer-live-p (eam-session-output viewer)))
        (with-current-buffer (eam-session-output viewer) (eam-detach)))
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (server-force-delete))
      (delete-directory eam-directory t))))
(ert-deftest eam-terminal-start-failure-is-isolated ()
  "Failures before and after PTY creation leave no session/buffer/process."
  (let* ((eam-directory (make-temp-file "ai-start-failure-" t))
         (args (list (expand-file-name "tests/terminal-fixture.py"
                                        eam-terminal-test-root)
                     (expand-file-name "received.jsonl" eam-directory)))
         (healthy (eam-terminal-start "healthy" (eam--executable "python3")
                                           args eam-directory))
         (original-exec (symbol-function 'ghostel-exec))
         failed-process)
    (unwind-protect
        (dolist (phase '(editor pty display))
          (let* ((name (format "failed-%s" phase))
                 (before (copy-sequence eam-terminal--sessions))
                 (before-processes (process-list))
                 (failure (lambda (&rest _) (error "Injected startup failure")))
                 (symbol (pcase phase ('editor 'eam-terminal--editor-command)
                                ('pty 'ghostel-exec) ('display 'pop-to-buffer))))
            (cl-letf (((symbol-function symbol)
                       (if (eq phase 'pty)
                           (lambda (&rest call-args)
                             (setq failed-process (apply original-exec call-args))
                             (error "Injected startup failure"))
                         failure)))
              (should (equal (should-error
                              (eam-terminal-start name (eam--executable "python3")
                                                       args eam-directory))
                             '(error "Injected startup failure"))))
            (should-not (get-buffer (eam-terminal--buffer-name name eam-directory)))
            (should-not (and failed-process (process-live-p failed-process)))
            (dolist (process (cl-set-difference (process-list) before-processes))
              (should-not (process-live-p process)))
            (should (equal before eam-terminal--sessions))
            (should (process-live-p (eam-terminal-process healthy)))))
      (dolist (name '("failed-editor" "failed-pty" "failed-display"))
        (when-let* ((buffer (get-buffer (eam-terminal--buffer-name name eam-directory))))
          (when-let* ((process (get-buffer-process buffer))) (delete-process process))
          (kill-buffer buffer)))
      (with-current-buffer (eam-terminal-output healthy) (eam-detach))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (server-force-delete))
      (delete-directory eam-directory t))))
(ert-deftest eam-terminal-recording-failure-is-isolated ()
  "A failed archive stops that PTY without delivering unrecorded output."
  (let ((eam-directory (make-temp-file "ai-pty-failure-" t))
        sessions)
    (unwind-protect
        (progn
          (dotimes (i 2)
            (push (eam-terminal-start
                   (format "failure-%d" i) (eam--executable "python3")
                   (list (expand-file-name "tests/terminal-fixture.py"
                                           eam-terminal-test-root)
                         (expand-file-name (format "received-%d.jsonl" i)
                                           eam-directory))
                   eam-directory) sessions))
          (dolist (s sessions)
            (eam-terminal-test-wait
             (lambda () (with-current-buffer (eam-terminal-output s)
                          (ghostel--mode-enabled ghostel--term 2004)))))
          (let ((failed (car sessions)) (healthy (cadr sessions)))
            (setf (eam-terminal-file failed)
                  (expand-file-name "missing/archive.ansi" eam-directory))
            (eam-terminal--filter failed (eam-terminal-process failed)
                                       "MUST_NOT_REACH_DISPLAY")
            (should (eam-terminal-error failed))
            (should-not (process-live-p (eam-terminal-process failed)))
            (with-current-buffer (eam-terminal-output failed)
              (should-not (string-match-p "MUST_NOT_REACH_DISPLAY" (buffer-string)))
              (should-error (eam-terminal-key "return") :type 'user-error))
            (should (process-live-p (eam-terminal-process healthy)))
            (with-current-buffer (eam-terminal-output healthy)
              (eam-terminal-key "return"))
            (eam-terminal-test-wait
             (lambda () (with-temp-buffer
                          (insert-file-contents (eam-terminal-file healthy))
                          (search-forward "ENTER" nil t))))
            (should-not (eam-terminal-error healthy))))
      (dolist (s sessions)
        (when (buffer-live-p (eam-terminal-output s))
          (with-current-buffer (eam-terminal-output s)
            (eam-detach))))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (server-force-delete))
      (delete-directory eam-directory t))))
(ert-deftest eam-terminal-empty-editor-and-byte-limit ()
  "An empty CLI draft can be edited; the paste limit counts UTF-8 bytes."
  (let* ((eam-directory (make-temp-file (concat "ai-paste-limit-" (make-string 100 ?x)) t))
         (log (expand-file-name "입력 기록.jsonl" eam-directory))
         (payload (concat (make-string 21844 ?가) "🙂"))
         (s (eam-terminal-start
             "byte-limit" (eam--executable "python3")
             (list (expand-file-name "tests/terminal-fixture.py" eam-terminal-test-root) log)
             eam-directory)))
    (unwind-protect
        (progn
          (should (= (string-bytes payload) 65536))
          (eam-terminal-test-wait
           (lambda () (with-current-buffer (eam-terminal-output s)
                        (ghostel--mode-enabled ghostel--term 2004))))
          (with-current-buffer (eam-terminal-output s) (eam-edit-input))
          (let ((file (concat (file-name-sans-extension log) ".editor.txt")))
            (eam-terminal-test-wait (lambda () (find-buffer-visiting file)))
            (with-current-buffer (find-buffer-visiting file)
              (should (zerop (buffer-size)))
              (insert "빈 입력에서 작성") (call-interactively (key-binding (kbd "C-c C-c")))))
          (eam-terminal-test-wait (lambda () (file-exists-p log)))
          (with-current-buffer (eam-terminal--ensure-draft s)
            (insert payload) (eam-paste))
          (eam-terminal-test-wait
           (lambda () (with-temp-buffer
                        (insert-file-contents log)
                        (search-forward "\"paste\"" nil t))))
          (let* ((lines (with-temp-buffer (insert-file-contents log)
                                         (split-string (buffer-string) "\n" t)))
                 (last (json-parse-string (car (last lines)) :object-type 'alist))
                 (record-size (file-attribute-size (file-attributes (eam-terminal-input-file s)))))
            (should (equal (alist-get 'paste last) payload))
            (with-current-buffer (eam-terminal-input s)
              (insert "a")
              (should-error (eam-paste) :type 'user-error)
              (should (= (buffer-size) (1+ (length payload)))))
            (should (= record-size (file-attribute-size (file-attributes (eam-terminal-input-file s)))))))
      (when (buffer-live-p (eam-terminal-output s))
        (with-current-buffer (eam-terminal-output s) (eam-detach)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (server-force-delete))
      (delete-directory eam-directory t))))
(ert-deftest eam-terminal-paste-and-native-keys ()
  (let* ((eam-directory (make-temp-file "ai-pty-test-" t))
         (log (expand-file-name "received.jsonl" eam-directory))
         (s (eam-terminal-start
             "fixture" (eam--executable "python3")
             (list (expand-file-name "tests/terminal-fixture.py" eam-terminal-test-root) log)
             eam-directory)))
    (unwind-protect
        (progn
          (should-not (eam-terminal-input s))
          (should (eq (current-buffer) (eam-terminal-output s)))
          (eam-draft)
          (eam-terminal-test-wait
           (lambda () (with-current-buffer (eam-terminal-output s)
                        (ghostel--mode-enabled ghostel--term 2004))))
          (eam-keys-mode 1)
          (with-current-buffer (eam-terminal-output s)
            (dolist (mode '(ghostel-copy-mode ghostel-emacs-mode ghostel-semi-char-mode))
              (funcall mode)
              (should (eq (key-binding (kbd "C-c a b")) #'eam-draft)))
            (ghostel-char-mode)
            (should (eq (key-binding (kbd "M-RET")) #'ghostel-semi-char-mode))
            (ghostel-semi-char-mode))
          (with-current-buffer (eam-terminal-output s)
            (dolist (mode '(ghostel-copy-mode ghostel-emacs-mode ghostel-char-mode ghostel-semi-char-mode))
              (funcall mode)
              (should-not (key-binding (vector 'menu-bar (intern "Terminal AI"))))))
          (with-current-buffer (eam-terminal-input s)
            (insert "한글🙂 첫 줄\n두 번째 줄") (undo-boundary)
            (insert "수정") (undo-boundary) (undo 1)
            (eam-paste))
          (eam-terminal-test-wait (lambda () (file-exists-p log)))
          (should (equal (with-temp-buffer (insert-file-contents log)
                                          (json-parse-string (buffer-string) :object-type 'alist))
                         '((paste . "한글🙂 첫 줄\n두 번째 줄"))))
          (with-current-buffer (eam-terminal-input s) (eam-terminal-key "return"))
          (eam-terminal-test-wait
           (lambda () (with-temp-buffer (insert-file-contents log) (search-forward "enter" nil t))))
          (with-current-buffer (eam-terminal-input s)
            (erase-buffer) (insert "/model") (eam-paste))
          (eam-terminal-test-wait
           (lambda () (with-temp-buffer (insert-file-contents log) (search-forward "/model" nil t))))
          (with-current-buffer (eam-terminal-output s) (eam-edit-input))
          (let ((editor-file (concat (file-name-sans-extension log) ".editor.txt")))
            (eam-terminal-test-wait (lambda ()
              (when-let* ((buffer (find-buffer-visiting editor-file)))
                (with-current-buffer buffer
                  (and eam-terminal-editor-mode server-buffer-clients)))))
            (with-current-buffer (find-buffer-visiting editor-file)
              (should (equal (buffer-string) "/model"))
              (should (string-match-p "C-c C-k" header-line-format))
              (should-not (eq buffer-undo-list t))
              (erase-buffer) (insert "편집한 한글🙂\n둘째 줄")
              (call-interactively (key-binding (kbd "C-c C-c")))))
          (eam-terminal-test-wait
           (lambda () (with-temp-buffer (insert-file-contents log) (search-forward "edited" nil t))))
          (with-current-buffer (eam-terminal-output s) (eam-edit-input))
          (let ((editor-file (concat (file-name-sans-extension log) ".editor.txt")))
            (eam-terminal-test-wait (lambda ()
              (when-let* ((buffer (find-buffer-visiting editor-file)))
                (with-current-buffer buffer
                  (and eam-terminal-editor-mode server-buffer-clients)))))
            (with-current-buffer (find-buffer-visiting editor-file)
              (should (equal (buffer-string) "편집한 한글🙂\n둘째 줄"))
              (erase-buffer) (insert "취소할 수정") (save-buffer)
              (call-interactively (key-binding (kbd "C-c C-k"))))
            (eam-terminal-test-wait
             (lambda ()
               (with-temp-buffer
                 (insert-file-contents log)
                 (= 2 (cl-count-if
                       (lambda (line) (string-match-p "\"edited\"" line))
                       (split-string (buffer-string) "\n" t))))))
            (let ((last (with-temp-buffer
                          (insert-file-contents log)
                          (car (last (split-string (buffer-string) "\n" t))))))
              (should (equal (alist-get 'edited (json-parse-string last :object-type 'alist))
                             "편집한 한글🙂\n둘째 줄"))))
          (with-current-buffer (eam-terminal-output s)
            (should (eq buffer-undo-list t)))
          (should (> (file-attribute-size (file-attributes (eam-terminal-file s))) 0))
          (with-current-buffer (eam-terminal-input s)
            (erase-buffer) (insert "unsafe\e[201~")
            (should-error (eam-paste) :type 'user-error)
            (set-buffer-modified-p nil)
            (kill-buffer (current-buffer)))
          (should (process-live-p (eam-terminal-process s)))
          (with-current-buffer (eam-terminal-output s) (eam-draft))
          (should (buffer-live-p (eam-terminal-input s)))
          (with-current-buffer (eam-terminal-output s) (eam-terminal-key "c" "ctrl"))
          (eam-terminal-test-wait (lambda () (not (process-live-p (eam-terminal-process s)))))
          ;; Process death precedes the sentinel's displayed exit message.
          (eam-terminal-test-wait
           (lambda () (with-current-buffer (eam-terminal-output s)
                        (string-match-p "Process exited" (buffer-string)))))
          (should (buffer-live-p (eam-terminal-output s)))
          (with-current-buffer (eam-terminal-output s)
            (should (eq buffer-undo-list t))
            (should (string-match-p "Process exited" (buffer-string)))))
      (with-current-buffer (eam-terminal-input s) (eam-detach))
      (should-not (process-live-p (eam-terminal-process s)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (server-force-delete))
      (delete-directory eam-directory t))))
