;;; usage-test.el --- Passive header lifecycle tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(defun eam-usage-test--both-rows ()
  (concat (eam-usage--account-header) "\n" (eam-usage--header)))
(ert-deftest eam-usage-header-does-not-query-during-redisplay ()
  (with-temp-buffer
    (setq-local eam-usage-display t eam-account-display t)
    (setq eam-usage--label "한글 세션" eam-usage--snapshot
          '((state . "available") (scope . "last") (input . 1200) (output . 30)
            (cached . 1000) (cache_write . 500) (source . "selected")))
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (ert-fail "Process in redisplay")))
              ((symbol-function 'insert-file-contents) (lambda (&rest _) (ert-fail "Disk in redisplay"))))
      (should (string-match-p "last in 1.2k / out 30" (eam-usage-test--both-rows)))
      (should-not (string-match-p "\\[selected\\]" (eam-usage-test--both-rows)))
      (should (string-match-p "write 500" (eam-usage-test--both-rows)))
      (setq eam-usage--snapshot '((state . "unbound")))
      (should-not (string-match-p "eam-usage\\|eam-detach\\|eam-quit\\|대화 선택" (eam-usage-test--both-rows)))
      (setq eam-usage-display nil)
      (should (equal (eam-usage--text) "")))))
(ert-deftest eam-usage-hidden-buffer-does-not-spawn-and-kill-cancels-timer ()
  (let ((buffer (generate-new-buffer " *eam-usage-test*")) timer)
    (unwind-protect
        (with-current-buffer buffer
          (setq-local eam-terminal-persistent-directory "/tmp/fake")
          (eam-usage--install "테스트")
          (setq timer eam-usage--timer)
          (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (ert-fail "Hidden worker"))))
            (eam-usage--refresh buffer))
          (should (timerp timer)))
      (kill-buffer buffer))
    (should-not (memq timer timer-list))))
(ert-deftest eam-usage-async-native-unbound-and-cleanup ()
  (skip-unless (or (getenv "EAM_NATIVE_BIN")
                   (and (stringp eam-native-executable) (file-executable-p eam-native-executable))))
  (let* ((buffer (generate-new-buffer " *eam-usage-worker*"))
         (eam-native-executable (or (getenv "EAM_NATIVE_BIN") eam-native-executable))
         (eam-usage--workers 0))
    (unwind-protect
        (with-current-buffer buffer
          (setq-local eam-terminal-persistent-directory "/tmp/no-such-eam-session"
                      eam-terminal--current (eam-terminal--session :name "Codex"))
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) t)))
            (eam-usage--refresh buffer))
          (let ((deadline (+ (float-time) 6)))
            (while (and (> eam-usage--workers 0) (< (float-time) deadline))
              (accept-process-output nil .02)))
          (should (= eam-usage--workers 0))
          (should-not (process-live-p eam-usage--process))
          (should-not eam-usage--snapshot))
      (kill-buffer buffer))))
(ert-deftest eam-usage-busy-readers-queue-one-retry-and-cancel ()
  (let ((buffer (generate-new-buffer " *eam-usage-busy*"))
        (eam-usage--workers 2) retry)
    (unwind-protect
        (with-current-buffer buffer
          (setq-local eam-terminal-persistent-directory "/tmp/fake")
          (eam-usage--install "queued")
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) t))
                    ((symbol-function 'make-process) (lambda (&rest _) (ert-fail "Exceeded worker limit"))))
            (eam-usage--refresh buffer)
            (setq retry eam-usage--retry)
            (should (timerp retry))
            (eam-usage--refresh buffer)
            (should (eq retry eam-usage--retry))))
      (kill-buffer buffer))
    (should-not (memq retry timer-list))
    (should (= eam-usage--workers 2))))
(ert-deftest eam-account-header-independent-of-usage-and-opt-out ()
  (with-temp-buffer
    (setq-local eam-usage-display t eam-account-display t)
    (setq eam-usage--snapshot '((state . "unbound")
                                (account . ((state . "local") (email . "user@example.test")
                                            (plan . "plus"))))
          eam-usage-display nil)
    (should (string-match-p "user@example.test (plus)" (eam-usage-test--both-rows)))
    (should-not (string-match-p "usage:" (eam-usage-test--both-rows)))
    (setq eam-account-display nil
          eam-terminal--current (eam-terminal--session :name "Codex"))
    (should-not (string-match-p "user@example.test" (eam-usage-test--both-rows)))
    (should-not (string-match-p "user@example.test" (get-text-property 0 'help-echo (eam-usage-test--both-rows))))
    (should (eq (alist-get 'account (eam-usage--request)) :json-false))))
(ert-deftest eam-usage-shows-provider-and-session-without-selector ()
  (with-temp-buffer
    (setq-local eam-usage-display t eam-account-display t)
    (setq eam-usage--snapshot
          '((state . "available") (scope . "total") (input . 1200) (output . 300)
            (context_percent . 42)
            (account . ((state . "local") (email . "user@example.test") (plan . "prolite")))
            (provider_usage . ((windows . [((minutes . 300) (used . 25))
                                           ((minutes . 10080) (used . 60))])))))
    (let ((header (eam-usage-test--both-rows)))
      (should (string-match-p "5h 25% used" header))
      (should (string-match-p "7d 60% used" header))
      (should (string-match-p "total in 1.2k / out 300" header))
      (should (string-match-p "ctx 42%" header))
      (should (string-match-p "prolite" header))
      (should-not (string-match-p "local account:\\|대화 선택\\|eam-detach\\|eam-quit" header)))
    (setq eam-terminal--current (eam-terminal--session :output (current-buffer)))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (ert-fail "Unexpected selector")))
              ((symbol-function 'eam-usage--refresh) (lambda (buffer force) (should force) (should (eq buffer (current-buffer))))))
      (eam-usage))))

(ert-deftest eam-usage-two-rows-and-explicit-plan-label ()
  (with-temp-buffer
    (setq-local eam-usage-display t eam-account-display t)
    (setq eam-terminal--current (eam-terminal--session :name "Codex")
          eam-usage--snapshot '((state . "available") (scope . "total")
                                (model . "MODEL-NOT-IN-HEADER") (input . 1200) (output . 300)
                                (account . ((state . "local") (email . "user@example.test") (plan . "pro")))))
    (let ((eam-account-plan-labels '(("Codex" ("pro" . "Pro 20x")))))
      (should (string-match-p "Pro 20x" (eam-usage--account-header)))
      (should-not (string-match-p "total in" (eam-usage--account-header)))
      (should (string-match-p "total in" (eam-usage--header)))
      (should-not (string-match-p "user@example" (eam-usage--header)))
      (should-not (string-match-p "provider:\\|session:\\|MODEL-NOT-IN-HEADER"
                                 (eam-usage-test--both-rows)))
      (should (equal (alist-get 'plan (alist-get 'account eam-usage--snapshot)) "pro")))
    (setq-local tab-line-format '("original tabs"))
    (eam-usage--install "Test")
    (should (equal tab-line-format '(:eval (eam-usage--literal (eam-usage--account-header)))))
    (should (equal header-line-format '(:eval (eam-usage--literal (eam-usage--header)))))
    (eam-usage--install "Renamed")
    (eam-usage--cancel)
    (should (equal tab-line-format '("original tabs")))))

(ert-deftest eam-usage-percent-is-escaped-only-at-display-boundary ()
  (with-temp-buffer
    (setq-local eam-usage-display t eam-account-display nil)
    (setq eam-usage--label "100% task"
          eam-usage--snapshot '((state . "available") (scope . "total")
                                (input . 10) (output . 2) (context_percent . 42)
                                (provider_usage . ((windows . [((minutes . 300) (used . 25))])))))
    (unwind-protect
        (progn
          (eam-usage--install "100% task")
          (should (string-match-p "100%% task" (eval (cadr tab-line-format))))
          (should (string-match-p "25%% used" (eval (cadr tab-line-format))))
          (should (string-match-p "ctx 42%%" (eval (cadr header-line-format))))
          (should (string-match-p "25% used" (eam-usage--account-header)))
          (should (string-match-p "ctx 42%" (eam-usage--header))))
      (eam-usage--cancel))))
