;;; worktree-live.el --- Real CLI startup only, no prompt -*- lexical-binding: t; -*-
(require 'eam-app)
(load (expand-file-name "tests/worktree-test.el" default-directory) nil t)
(let* ((root (file-name-as-directory (getenv "EMACS_AI_WORKTREE_PROBE")))
       (eam-directory (expand-file-name "records/" root))
       (repo (eam-worktree-test-repo root)) sessions results)
  (unwind-protect
      (progn
        (dolist (provider '("Claude" "Codex"))
          (let* ((path (expand-file-name (concat provider " 한글 worktree") root))
                 (created (eam-worktree--create repo path (concat "probe/" provider) "HEAD"))
                 (entry (cl-find-if (lambda (e) (equal (file-truename created)
                                                       (file-truename (plist-get e :path))))
                                    (eam-worktree--list repo)))
                 (session
                  (cl-letf (((symbol-function 'eam-worktree--choose) (lambda (_) entry))
                            ((symbol-function 'completing-read) (lambda (&rest _) provider)))
                    (eam-worktree-start repo))))
            (push session sessions)
            (let ((end (+ (float-time) 5)))
              (while (< (float-time) end) (accept-process-output nil .1)))
            (let* ((process (eam-terminal-process session))
                   (cwd (with-temp-buffer
                          (unless (= 0 (process-file "/usr/sbin/lsof" nil t nil "-a" "-p"
                                                      (number-to-string (process-id process)) "-d" "cwd" "-Fn"))
                            (error "Cannot inspect native process cwd"))
                          (goto-char (point-min))
                          (unless (re-search-forward "^n\\(.+\\)$" nil t) (error "No native cwd"))
                          (match-string-no-properties 1))))
              (should (process-live-p process))
              (should (equal (file-truename cwd) (file-truename path)))
              (should-error (eam-worktree--remove repo path) :type 'user-error)
              (should (file-directory-p path))
              (with-current-buffer (eam-terminal-output session)
                (ghostel--redraw-now (current-buffer) t)
                (write-region (point-min) (point-max) (expand-file-name (concat provider "-screen.txt") root) nil 'silent))
              (push `((provider . ,provider) (native_cwd . ,cwd) (selected_path . ,path)
                      (command . ,(vconcat (process-command process)))
                      (input_bytes . ,(file-attribute-size (file-attributes (eam-terminal-input-file session))))
                      (deletion_guard . t)) results))))
        (with-temp-file (expand-file-name "result.json" root)
          (insert (json-encode (vconcat (nreverse results))))))
    (dolist (session sessions)
      (when (buffer-live-p (eam-terminal-output session))
        (with-current-buffer (eam-terminal-output session) (eam-detach))))
    (server-force-delete)))
