;;; workflow-switch.el --- Project switch in a running batch harness -*- lexical-binding: t; -*-
(require 'eam-app)
(let* ((main ai-validation-session)
       (provider ai-validation-provider)
       (directory (expand-file-name "other-project" ai-validation-dir))
       (args (if (equal provider "claude") '("--permission-mode" "manual")
               (list "-c" (concat "projects={" (json-encode-string directory)
                                  "={trust_level=\"trusted\"}}")
                     "--sandbox" "read-only" "--ask-for-approval" "on-request")))
       (other (eam-terminal-start provider (eam--executable provider) args directory)))
  (unwind-protect
      (progn
        ;; This drives the real selector with a deterministic completion answer.
        ;; It validates session routing, not a GUI completion popup.
        (dolist (s (list main other main))
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (&rest _) (buffer-name (eam-terminal-output s)))))
            (eam-sessions))
          (cl-assert (eq (current-buffer) (eam-terminal-output s)))
          (cl-assert (equal default-directory (eam-terminal-directory s)))
          (cl-assert (process-live-p (eam-terminal-process s))))
        (pop-to-buffer (eam-terminal-output other))
        ;; Bracketed paste and the title appear before startup completes.
        ;; Inspect the selected, rendered terminal, not raw ANSI word spacing.
        (let ((end (+ (float-time) 25)) ready)
          (while (and (< (float-time) end) (not ready))
            (accept-process-output nil .1)
            (setq ready
                  (with-current-buffer (eam-terminal-output other)
                    (ghostel--redraw-now (current-buffer) t)
                    (if (equal provider "claude")
                        (string-match-p "manual mode on" (buffer-string))
                      (and (string-match-p "gpt-" (buffer-string))
                           (not (string-match-p "loading" (buffer-string))))))))
          (unless ready (error "Secondary CLI did not finish startup")))
        (accept-process-output nil 1)
        (with-current-buffer (eam-terminal-output other)
          (cl-assert (ghostel--mode-enabled ghostel--term 2004))
          (ghostel--redraw-now (current-buffer) t)
          (ai-validation-write "other-project-screen.txt" (buffer-string))
          (ghostel-paste-string (if (equal provider "claude") "/exit" "/quit"))
          (eam-terminal-key "return"))
        (let ((end (+ (float-time) 12)))
          (while (and (process-live-p (eam-terminal-process other))
                      (< (float-time) end))
            (accept-process-output nil .1)))
        (cl-assert (not (process-live-p (eam-terminal-process other))))
        (cl-assert (process-live-p (eam-terminal-process main)))
        (ai-validation-write "switch-result.json"
          (json-encode `((provider . ,provider) (switches . 3)
                         (other-exit-code . ,(process-exit-status (eam-terminal-process other)))
                         (main-alive . t) (gui-tested . :json-false)))))
    (when (buffer-live-p (eam-terminal-output other))
      (with-current-buffer (eam-terminal-output other) (eam-detach)))
    (pop-to-buffer (eam-terminal-output main))))
