;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(defun eam-worktree-test-repo (root)
  (let ((repo (expand-file-name "main 저장소" root)))
    (make-directory repo)
    (eam-worktree--git repo "init" "--quiet")
    (with-temp-file (expand-file-name "tracked.txt" repo) (insert "base\n"))
    (with-temp-file (expand-file-name ".gitignore" repo) (insert "ignored\n"))
    (eam-worktree--git repo "add" ".")
    (eam-worktree--git repo "-c" "user.name=Worktree test" "-c" "user.email=test@example.invalid"
                           "-c" "core.hooksPath=/dev/null" "-c" "commit.gpgsign=false"
                           "commit" "--quiet" "-m" "fixture")
    repo))
(ert-deftest eam-worktree-create-isolate-and-select ()
  (let* ((root (make-temp-file "ai-worktree-" t))
         (repo (eam-worktree-test-repo root))
         (one (expand-file-name "work 한글 one" root))
         (two (expand-file-name "work two" root)) selected)
    (unwind-protect
        (progn
          ;; Exercise the abbreviated path returned by GUI directory prompts.
          (eam-worktree--create
           (concat "~/" (file-relative-name repo (expand-file-name "~/")))
           one "feature/한글" "HEAD")
          (eam-worktree--create repo two "feature/two" "HEAD")
          (should (= (length (eam-worktree--list repo)) 3))
          (should-error (eam-worktree--create repo one "another" "HEAD") :type 'user-error)
          (should-error (eam-worktree--create repo (expand-file-name "unused" root) "feature/two" "HEAD") :type 'user-error)
          (with-temp-file (expand-file-name "tracked.txt" one) (insert "isolated\n"))
          (dolist (dir (list repo two))
            (should (equal (with-temp-buffer (insert-file-contents (expand-file-name "tracked.txt" dir))
                                           (buffer-string)) "base\n")))
          (cl-letf (((symbol-function 'eam-worktree--choose)
                     (lambda (_) (cl-find one (eam-worktree--list repo)
                                          :key (lambda (entry) (plist-get entry :path))
                                          :test (lambda (a b) (equal (file-truename a) (file-truename b))))))
                    ((symbol-function 'completing-read) (lambda (&rest _) "Codex"))
                    ((symbol-function 'eam-terminal-start-provider) (lambda (provider dir) (should (equal provider "Codex")) (setq selected dir))))
            (eam-worktree-start repo)
            (should (equal (file-truename selected) (file-truename one)))))
      (delete-directory root t))))
(ert-deftest eam-worktree-remove-guards ()
  (let* ((root (make-temp-file "ai-worktree-" t))
         (repo (eam-worktree-test-repo root))
         (path (expand-file-name "linked" root))
         (eam-terminal--sessions nil) process buffer)
    (unwind-protect
        (progn
          (eam-worktree--create repo path "feature/remove" "HEAD")
          (should-error (eam-worktree--remove repo repo) :type 'user-error)
          (dolist (file '("tracked.txt" "untracked" "ignored"))
            (with-temp-file (expand-file-name file path) (insert "changed\n"))
            (should-error (eam-worktree--remove repo path) :type 'user-error)
            (should (file-directory-p path))
            (if (equal file "tracked.txt")
                (with-temp-file (expand-file-name file path) (insert "base\n"))
              (delete-file (expand-file-name file path))))
          (setq buffer (find-file-noselect (expand-file-name "tracked.txt" path)))
          (with-current-buffer buffer (insert "unsaved"))
          (should-error (eam-worktree--remove repo path) :type 'user-error)
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)
          (setq process (make-process :name "worktree-live" :command '("/bin/sleep" "10") :noquery t))
          (let ((eam-terminal--sessions (list (eam-terminal--session :directory path :process process))))
            (should-error (eam-worktree--remove repo path) :type 'user-error))
          (delete-process process)
          (eam-worktree--git repo "worktree" "lock" path)
          (should-error (eam-worktree--remove repo path) :type 'user-error)
          (eam-worktree--git repo "worktree" "unlock" path)
          (eam-worktree--remove repo path)
          (should-not (file-exists-p path))
          (should (string-match-p "refs/heads/feature/remove"
                                  (eam-worktree--git repo "show-ref" "--verify" "refs/heads/feature/remove"))))
      (when (and process (process-live-p process)) (delete-process process))
      (when (buffer-live-p buffer) (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest eam-worktree-bare-and-nul-paths ()
  (let* ((root (make-temp-file "ai-bare-" t))
         (repo (eam-worktree-test-repo root))
         (bare (expand-file-name "store.git" root))
         (path (expand-file-name "line\nbreak 한글" root)))
    (unwind-protect
        (progn
          (eam-worktree--git repo "clone" "--bare" "--no-hardlinks" repo bare)
          (eam-worktree--create bare path "feature/bare" "HEAD")
          (let ((entries (eam-worktree--list bare)))
            (should (plist-get (car entries) :bare))
            (should (equal (plist-get (cadr entries) :path) (file-truename path)))
            (should (equal (plist-get (cadr entries) :branch) "refs/heads/feature/bare")))
          (eam-worktree--remove bare path)
          (should-not (file-exists-p path)))
      (delete-directory root t))))

(ert-deftest eam-worktree-running-project-command-blocks-removal ()
  (let* ((root (make-temp-file "ai-worktree-task-" t))
         (repo (eam-worktree-test-repo root))
         (path (expand-file-name "linked" root))
         (eam-directory (expand-file-name "records/" root))
         buffer process)
    (unwind-protect
        (progn
          (eam-worktree--create repo path "feature/server" "HEAD")
          (require 'compile)
          (setq buffer (let ((default-directory (file-name-as-directory path)))
                         (compilation-start "exec sleep 20"))
                process (get-buffer-process buffer))
          (should-error (eam-worktree--remove repo path) :type 'user-error)
          (should (file-directory-p path))
          (with-current-buffer buffer (kill-compilation))
          (let ((end (+ (float-time) 5)))
            (while (and (process-live-p process) (< (float-time) end)) (accept-process-output nil .02)))
          (should-not (process-live-p process))
          (eam-worktree--remove repo path)
          (should-not (file-exists-p path)))
      (when (and process (process-live-p process)) (delete-process process))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory root t))))
